/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import type {
	AuthControllerGetUserParams,
	AuthControllerGetUserQuotaParams,
	UserDto,
	UserQuotaDto,
	UserWithCompanyDto,
} from "./models";
import { authInstance } from "../../instances/authInstance";
import type { ErrorType } from "../../instances/authInstance";

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export const authControllerStatus = (signal?: AbortSignal) => {
	return authInstance<UserWithCompanyDto>({ url: `/api/auth`, method: "GET", signal });
};

export const getAuthControllerStatusQueryKey = () => {
	return [`/api/auth`] as const;
};

export const getAuthControllerStatusQueryOptions = <
	TData = Awaited<ReturnType<typeof authControllerStatus>>,
	TError = ErrorType<unknown>,
>(options?: {
	query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerStatus>>, TError, TData>>;
}) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getAuthControllerStatusQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof authControllerStatus>>> = ({ signal }) =>
		authControllerStatus(signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof authControllerStatus>>,
		TError,
		TData
	> & { queryKey: QueryKey };
};

export type AuthControllerStatusQueryResult = NonNullable<
	Awaited<ReturnType<typeof authControllerStatus>>
>;
export type AuthControllerStatusQueryError = ErrorType<unknown>;

export function useAuthControllerStatus<
	TData = Awaited<ReturnType<typeof authControllerStatus>>,
	TError = ErrorType<unknown>,
>(options: {
	query: Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerStatus>>, TError, TData>> &
		Pick<
			DefinedInitialDataOptions<Awaited<ReturnType<typeof authControllerStatus>>, TError, TData>,
			"initialData"
		>;
}): DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useAuthControllerStatus<
	TData = Awaited<ReturnType<typeof authControllerStatus>>,
	TError = ErrorType<unknown>,
>(options?: {
	query?: Partial<
		UseQueryOptions<Awaited<ReturnType<typeof authControllerStatus>>, TError, TData>
	> &
		Pick<
			UndefinedInitialDataOptions<Awaited<ReturnType<typeof authControllerStatus>>, TError, TData>,
			"initialData"
		>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useAuthControllerStatus<
	TData = Awaited<ReturnType<typeof authControllerStatus>>,
	TError = ErrorType<unknown>,
>(options?: {
	query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerStatus>>, TError, TData>>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey };

export function useAuthControllerStatus<
	TData = Awaited<ReturnType<typeof authControllerStatus>>,
	TError = ErrorType<unknown>,
>(options?: {
	query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerStatus>>, TError, TData>>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
	const queryOptions = getAuthControllerStatusQueryOptions(options);

	const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

	query.queryKey = queryOptions.queryKey;

	return query;
}

export const authControllerGetUser = (
	params: AuthControllerGetUserParams,
	signal?: AbortSignal,
) => {
	return authInstance<UserDto>({ url: `/api/auth/user`, method: "GET", params, signal });
};

export const getAuthControllerGetUserQueryKey = (params: AuthControllerGetUserParams) => {
	return [`/api/auth/user`, ...(params ? [params] : [])] as const;
};

export const getAuthControllerGetUserQueryOptions = <
	TData = Awaited<ReturnType<typeof authControllerGetUser>>,
	TError = ErrorType<unknown>,
>(
	params: AuthControllerGetUserParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof authControllerGetUser>>, TError, TData>
		>;
	},
) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getAuthControllerGetUserQueryKey(params);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof authControllerGetUser>>> = ({ signal }) =>
		authControllerGetUser(params, signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof authControllerGetUser>>,
		TError,
		TData
	> & { queryKey: QueryKey };
};

export type AuthControllerGetUserQueryResult = NonNullable<
	Awaited<ReturnType<typeof authControllerGetUser>>
>;
export type AuthControllerGetUserQueryError = ErrorType<unknown>;

export function useAuthControllerGetUser<
	TData = Awaited<ReturnType<typeof authControllerGetUser>>,
	TError = ErrorType<unknown>,
>(
	params: AuthControllerGetUserParams,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof authControllerGetUser>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<Awaited<ReturnType<typeof authControllerGetUser>>, TError, TData>,
				"initialData"
			>;
	},
): DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useAuthControllerGetUser<
	TData = Awaited<ReturnType<typeof authControllerGetUser>>,
	TError = ErrorType<unknown>,
>(
	params: AuthControllerGetUserParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof authControllerGetUser>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof authControllerGetUser>>,
					TError,
					TData
				>,
				"initialData"
			>;
	},
): UseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useAuthControllerGetUser<
	TData = Awaited<ReturnType<typeof authControllerGetUser>>,
	TError = ErrorType<unknown>,
>(
	params: AuthControllerGetUserParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof authControllerGetUser>>, TError, TData>
		>;
	},
): UseQueryResult<TData, TError> & { queryKey: QueryKey };

export function useAuthControllerGetUser<
	TData = Awaited<ReturnType<typeof authControllerGetUser>>,
	TError = ErrorType<unknown>,
>(
	params: AuthControllerGetUserParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof authControllerGetUser>>, TError, TData>
		>;
	},
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
	const queryOptions = getAuthControllerGetUserQueryOptions(params, options);

	const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

	query.queryKey = queryOptions.queryKey;

	return query;
}

export const authControllerGetUserQuota = (
	params?: AuthControllerGetUserQuotaParams,
	signal?: AbortSignal,
) => {
	return authInstance<UserQuotaDto[]>({
		url: `/api/auth/getUserQuota`,
		method: "GET",
		params,
		signal,
	});
};

export const getAuthControllerGetUserQuotaQueryKey = (
	params?: AuthControllerGetUserQuotaParams,
) => {
	return [`/api/auth/getUserQuota`, ...(params ? [params] : [])] as const;
};

export const getAuthControllerGetUserQuotaQueryOptions = <
	TData = Awaited<ReturnType<typeof authControllerGetUserQuota>>,
	TError = ErrorType<unknown>,
>(
	params?: AuthControllerGetUserQuotaParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof authControllerGetUserQuota>>, TError, TData>
		>;
	},
) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getAuthControllerGetUserQuotaQueryKey(params);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof authControllerGetUserQuota>>> = ({
		signal,
	}) => authControllerGetUserQuota(params, signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof authControllerGetUserQuota>>,
		TError,
		TData
	> & { queryKey: QueryKey };
};

export type AuthControllerGetUserQuotaQueryResult = NonNullable<
	Awaited<ReturnType<typeof authControllerGetUserQuota>>
>;
export type AuthControllerGetUserQuotaQueryError = ErrorType<unknown>;

export function useAuthControllerGetUserQuota<
	TData = Awaited<ReturnType<typeof authControllerGetUserQuota>>,
	TError = ErrorType<unknown>,
>(
	params: undefined | AuthControllerGetUserQuotaParams,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof authControllerGetUserQuota>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof authControllerGetUserQuota>>,
					TError,
					TData
				>,
				"initialData"
			>;
	},
): DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useAuthControllerGetUserQuota<
	TData = Awaited<ReturnType<typeof authControllerGetUserQuota>>,
	TError = ErrorType<unknown>,
>(
	params?: AuthControllerGetUserQuotaParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof authControllerGetUserQuota>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof authControllerGetUserQuota>>,
					TError,
					TData
				>,
				"initialData"
			>;
	},
): UseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useAuthControllerGetUserQuota<
	TData = Awaited<ReturnType<typeof authControllerGetUserQuota>>,
	TError = ErrorType<unknown>,
>(
	params?: AuthControllerGetUserQuotaParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof authControllerGetUserQuota>>, TError, TData>
		>;
	},
): UseQueryResult<TData, TError> & { queryKey: QueryKey };

export function useAuthControllerGetUserQuota<
	TData = Awaited<ReturnType<typeof authControllerGetUserQuota>>,
	TError = ErrorType<unknown>,
>(
	params?: AuthControllerGetUserQuotaParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof authControllerGetUserQuota>>, TError, TData>
		>;
	},
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
	const queryOptions = getAuthControllerGetUserQuotaQueryOptions(params, options);

	const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

	query.queryKey = queryOptions.queryKey;

	return query;
}
