/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import type {
	AuthControllerGetGoogleClientId200,
	AuthControllerGetUserParams,
	AuthControllerGetUserQuotaParams,
	LoginSuccessDto,
	UserDto,
	UserQuotaDto,
	UserWithCompanyDto,
	VerifyGoogleTokenDto,
} from "./models";
import { authInstance } from "../../instances/authInstance";
import type { ErrorType } from "../../instances/authInstance";

export const authControllerStatus = (signal?: AbortSignal) => {
	return authInstance<UserWithCompanyDto>({ url: `/api/auth`, method: "GET", signal });
};

export const getAuthControllerStatusQueryKey = () => {
	return [`/api/auth`] as const;
};

export const getAuthControllerStatusQueryOptions = <
	TData = Awaited<ReturnType<typeof authControllerStatus>>,
	TError = ErrorType<unknown>,
>(options?: {
	query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerStatus>>, TError, TData>>;
}) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getAuthControllerStatusQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof authControllerStatus>>> = ({ signal }) =>
		authControllerStatus(signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof authControllerStatus>>,
		TError,
		TData
	> & { queryKey: QueryKey };
};

export type AuthControllerStatusQueryResult = NonNullable<
	Awaited<ReturnType<typeof authControllerStatus>>
>;
export type AuthControllerStatusQueryError = ErrorType<unknown>;

export function useAuthControllerStatus<
	TData = Awaited<ReturnType<typeof authControllerStatus>>,
	TError = ErrorType<unknown>,
>(options: {
	query: Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerStatus>>, TError, TData>> &
		Pick<
			DefinedInitialDataOptions<Awaited<ReturnType<typeof authControllerStatus>>, TError, TData>,
			"initialData"
		>;
}): DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useAuthControllerStatus<
	TData = Awaited<ReturnType<typeof authControllerStatus>>,
	TError = ErrorType<unknown>,
>(options?: {
	query?: Partial<
		UseQueryOptions<Awaited<ReturnType<typeof authControllerStatus>>, TError, TData>
	> &
		Pick<
			UndefinedInitialDataOptions<Awaited<ReturnType<typeof authControllerStatus>>, TError, TData>,
			"initialData"
		>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useAuthControllerStatus<
	TData = Awaited<ReturnType<typeof authControllerStatus>>,
	TError = ErrorType<unknown>,
>(options?: {
	query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerStatus>>, TError, TData>>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey };

export function useAuthControllerStatus<
	TData = Awaited<ReturnType<typeof authControllerStatus>>,
	TError = ErrorType<unknown>,
>(options?: {
	query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerStatus>>, TError, TData>>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
	const queryOptions = getAuthControllerStatusQueryOptions(options);

	const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

	query.queryKey = queryOptions.queryKey;

	return query;
}

export const authControllerGetUser = (
	params: AuthControllerGetUserParams,
	signal?: AbortSignal,
) => {
	return authInstance<UserDto>({ url: `/api/auth/user`, method: "GET", params, signal });
};

export const getAuthControllerGetUserQueryKey = (params: AuthControllerGetUserParams) => {
	return [`/api/auth/user`, ...(params ? [params] : [])] as const;
};

export const getAuthControllerGetUserQueryOptions = <
	TData = Awaited<ReturnType<typeof authControllerGetUser>>,
	TError = ErrorType<unknown>,
>(
	params: AuthControllerGetUserParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof authControllerGetUser>>, TError, TData>
		>;
	},
) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getAuthControllerGetUserQueryKey(params);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof authControllerGetUser>>> = ({ signal }) =>
		authControllerGetUser(params, signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof authControllerGetUser>>,
		TError,
		TData
	> & { queryKey: QueryKey };
};

export type AuthControllerGetUserQueryResult = NonNullable<
	Awaited<ReturnType<typeof authControllerGetUser>>
>;
export type AuthControllerGetUserQueryError = ErrorType<unknown>;

export function useAuthControllerGetUser<
	TData = Awaited<ReturnType<typeof authControllerGetUser>>,
	TError = ErrorType<unknown>,
>(
	params: AuthControllerGetUserParams,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof authControllerGetUser>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<Awaited<ReturnType<typeof authControllerGetUser>>, TError, TData>,
				"initialData"
			>;
	},
): DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useAuthControllerGetUser<
	TData = Awaited<ReturnType<typeof authControllerGetUser>>,
	TError = ErrorType<unknown>,
>(
	params: AuthControllerGetUserParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof authControllerGetUser>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof authControllerGetUser>>,
					TError,
					TData
				>,
				"initialData"
			>;
	},
): UseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useAuthControllerGetUser<
	TData = Awaited<ReturnType<typeof authControllerGetUser>>,
	TError = ErrorType<unknown>,
>(
	params: AuthControllerGetUserParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof authControllerGetUser>>, TError, TData>
		>;
	},
): UseQueryResult<TData, TError> & { queryKey: QueryKey };

export function useAuthControllerGetUser<
	TData = Awaited<ReturnType<typeof authControllerGetUser>>,
	TError = ErrorType<unknown>,
>(
	params: AuthControllerGetUserParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof authControllerGetUser>>, TError, TData>
		>;
	},
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
	const queryOptions = getAuthControllerGetUserQueryOptions(params, options);

	const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

	query.queryKey = queryOptions.queryKey;

	return query;
}

export const authControllerGetUserQuota = (
	params?: AuthControllerGetUserQuotaParams,
	signal?: AbortSignal,
) => {
	return authInstance<UserQuotaDto[]>({
		url: `/api/auth/getUserQuota`,
		method: "GET",
		params,
		signal,
	});
};

export const getAuthControllerGetUserQuotaQueryKey = (
	params?: AuthControllerGetUserQuotaParams,
) => {
	return [`/api/auth/getUserQuota`, ...(params ? [params] : [])] as const;
};

export const getAuthControllerGetUserQuotaQueryOptions = <
	TData = Awaited<ReturnType<typeof authControllerGetUserQuota>>,
	TError = ErrorType<unknown>,
>(
	params?: AuthControllerGetUserQuotaParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof authControllerGetUserQuota>>, TError, TData>
		>;
	},
) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getAuthControllerGetUserQuotaQueryKey(params);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof authControllerGetUserQuota>>> = ({
		signal,
	}) => authControllerGetUserQuota(params, signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof authControllerGetUserQuota>>,
		TError,
		TData
	> & { queryKey: QueryKey };
};

export type AuthControllerGetUserQuotaQueryResult = NonNullable<
	Awaited<ReturnType<typeof authControllerGetUserQuota>>
>;
export type AuthControllerGetUserQuotaQueryError = ErrorType<unknown>;

export function useAuthControllerGetUserQuota<
	TData = Awaited<ReturnType<typeof authControllerGetUserQuota>>,
	TError = ErrorType<unknown>,
>(
	params: undefined | AuthControllerGetUserQuotaParams,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof authControllerGetUserQuota>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof authControllerGetUserQuota>>,
					TError,
					TData
				>,
				"initialData"
			>;
	},
): DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useAuthControllerGetUserQuota<
	TData = Awaited<ReturnType<typeof authControllerGetUserQuota>>,
	TError = ErrorType<unknown>,
>(
	params?: AuthControllerGetUserQuotaParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof authControllerGetUserQuota>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof authControllerGetUserQuota>>,
					TError,
					TData
				>,
				"initialData"
			>;
	},
): UseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useAuthControllerGetUserQuota<
	TData = Awaited<ReturnType<typeof authControllerGetUserQuota>>,
	TError = ErrorType<unknown>,
>(
	params?: AuthControllerGetUserQuotaParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof authControllerGetUserQuota>>, TError, TData>
		>;
	},
): UseQueryResult<TData, TError> & { queryKey: QueryKey };

export function useAuthControllerGetUserQuota<
	TData = Awaited<ReturnType<typeof authControllerGetUserQuota>>,
	TError = ErrorType<unknown>,
>(
	params?: AuthControllerGetUserQuotaParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof authControllerGetUserQuota>>, TError, TData>
		>;
	},
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
	const queryOptions = getAuthControllerGetUserQuotaQueryOptions(params, options);

	const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

	query.queryKey = queryOptions.queryKey;

	return query;
}

export const authControllerVerifyGoogleToken = (verifyGoogleTokenDto: VerifyGoogleTokenDto) => {
	return authInstance<LoginSuccessDto>({
		url: `/api/auth/verify-google-token`,
		method: "POST",
		headers: { "Content-Type": "application/json" },
		data: verifyGoogleTokenDto,
	});
};

export const getAuthControllerVerifyGoogleTokenMutationOptions = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof authControllerVerifyGoogleToken>>,
		TError,
		{ data: VerifyGoogleTokenDto },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof authControllerVerifyGoogleToken>>,
	TError,
	{ data: VerifyGoogleTokenDto },
	TContext
> => {
	const { mutation: mutationOptions } = options ?? {};

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof authControllerVerifyGoogleToken>>,
		{ data: VerifyGoogleTokenDto }
	> = (props) => {
		const { data } = props ?? {};

		return authControllerVerifyGoogleToken(data);
	};

	return { mutationFn, ...mutationOptions };
};

export type AuthControllerVerifyGoogleTokenMutationResult = NonNullable<
	Awaited<ReturnType<typeof authControllerVerifyGoogleToken>>
>;
export type AuthControllerVerifyGoogleTokenMutationBody = VerifyGoogleTokenDto;
export type AuthControllerVerifyGoogleTokenMutationError = ErrorType<unknown>;

export const useAuthControllerVerifyGoogleToken = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof authControllerVerifyGoogleToken>>,
		TError,
		{ data: VerifyGoogleTokenDto },
		TContext
	>;
}): UseMutationResult<
	Awaited<ReturnType<typeof authControllerVerifyGoogleToken>>,
	TError,
	{ data: VerifyGoogleTokenDto },
	TContext
> => {
	const mutationOptions = getAuthControllerVerifyGoogleTokenMutationOptions(options);

	return useMutation(mutationOptions);
};
export const authControllerGetGoogleClientId = (signal?: AbortSignal) => {
	return authInstance<AuthControllerGetGoogleClientId200>({
		url: `/api/auth/google-client-id`,
		method: "GET",
		signal,
	});
};

export const getAuthControllerGetGoogleClientIdQueryKey = () => {
	return [`/api/auth/google-client-id`] as const;
};

export const getAuthControllerGetGoogleClientIdQueryOptions = <
	TData = Awaited<ReturnType<typeof authControllerGetGoogleClientId>>,
	TError = ErrorType<unknown>,
>(options?: {
	query?: Partial<
		UseQueryOptions<Awaited<ReturnType<typeof authControllerGetGoogleClientId>>, TError, TData>
	>;
}) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getAuthControllerGetGoogleClientIdQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof authControllerGetGoogleClientId>>> = ({
		signal,
	}) => authControllerGetGoogleClientId(signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof authControllerGetGoogleClientId>>,
		TError,
		TData
	> & { queryKey: QueryKey };
};

export type AuthControllerGetGoogleClientIdQueryResult = NonNullable<
	Awaited<ReturnType<typeof authControllerGetGoogleClientId>>
>;
export type AuthControllerGetGoogleClientIdQueryError = ErrorType<unknown>;

export function useAuthControllerGetGoogleClientId<
	TData = Awaited<ReturnType<typeof authControllerGetGoogleClientId>>,
	TError = ErrorType<unknown>,
>(options: {
	query: Partial<
		UseQueryOptions<Awaited<ReturnType<typeof authControllerGetGoogleClientId>>, TError, TData>
	> &
		Pick<
			DefinedInitialDataOptions<
				Awaited<ReturnType<typeof authControllerGetGoogleClientId>>,
				TError,
				TData
			>,
			"initialData"
		>;
}): DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useAuthControllerGetGoogleClientId<
	TData = Awaited<ReturnType<typeof authControllerGetGoogleClientId>>,
	TError = ErrorType<unknown>,
>(options?: {
	query?: Partial<
		UseQueryOptions<Awaited<ReturnType<typeof authControllerGetGoogleClientId>>, TError, TData>
	> &
		Pick<
			UndefinedInitialDataOptions<
				Awaited<ReturnType<typeof authControllerGetGoogleClientId>>,
				TError,
				TData
			>,
			"initialData"
		>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useAuthControllerGetGoogleClientId<
	TData = Awaited<ReturnType<typeof authControllerGetGoogleClientId>>,
	TError = ErrorType<unknown>,
>(options?: {
	query?: Partial<
		UseQueryOptions<Awaited<ReturnType<typeof authControllerGetGoogleClientId>>, TError, TData>
	>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey };

export function useAuthControllerGetGoogleClientId<
	TData = Awaited<ReturnType<typeof authControllerGetGoogleClientId>>,
	TError = ErrorType<unknown>,
>(options?: {
	query?: Partial<
		UseQueryOptions<Awaited<ReturnType<typeof authControllerGetGoogleClientId>>, TError, TData>
	>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
	const queryOptions = getAuthControllerGetGoogleClientIdQueryOptions(options);

	const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

	query.queryKey = queryOptions.queryKey;

	return query;
}
