/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import type {
	CouponsControllerCreate200,
	CouponsControllerUpdate200,
	CouponsDto,
	CreateCouponsDto,
	UpdateCouponsDto,
} from "./models";
import { authInstance } from "../../instances/authInstance";
import type { ErrorType } from "../../instances/authInstance";

export const couponsControllerCreate = (createCouponsDto: CreateCouponsDto) => {
	return authInstance<CouponsControllerCreate200 | void>({
		url: `/api/coupons`,
		method: "POST",
		headers: { "Content-Type": "application/json" },
		data: createCouponsDto,
	});
};

export const getCouponsControllerCreateMutationOptions = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof couponsControllerCreate>>,
		TError,
		{ data: CreateCouponsDto },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof couponsControllerCreate>>,
	TError,
	{ data: CreateCouponsDto },
	TContext
> => {
	const { mutation: mutationOptions } = options ?? {};

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof couponsControllerCreate>>,
		{ data: CreateCouponsDto }
	> = (props) => {
		const { data } = props ?? {};

		return couponsControllerCreate(data);
	};

	return { mutationFn, ...mutationOptions };
};

export type CouponsControllerCreateMutationResult = NonNullable<
	Awaited<ReturnType<typeof couponsControllerCreate>>
>;
export type CouponsControllerCreateMutationBody = CreateCouponsDto;
export type CouponsControllerCreateMutationError = ErrorType<unknown>;

export const useCouponsControllerCreate = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof couponsControllerCreate>>,
		TError,
		{ data: CreateCouponsDto },
		TContext
	>;
}): UseMutationResult<
	Awaited<ReturnType<typeof couponsControllerCreate>>,
	TError,
	{ data: CreateCouponsDto },
	TContext
> => {
	const mutationOptions = getCouponsControllerCreateMutationOptions(options);

	return useMutation(mutationOptions);
};
export const couponsControllerFindAll = (signal?: AbortSignal) => {
	return authInstance<CouponsDto[]>({ url: `/api/coupons`, method: "GET", signal });
};

export const getCouponsControllerFindAllQueryKey = () => {
	return [`/api/coupons`] as const;
};

export const getCouponsControllerFindAllQueryOptions = <
	TData = Awaited<ReturnType<typeof couponsControllerFindAll>>,
	TError = ErrorType<unknown>,
>(options?: {
	query?: Partial<
		UseQueryOptions<Awaited<ReturnType<typeof couponsControllerFindAll>>, TError, TData>
	>;
}) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getCouponsControllerFindAllQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof couponsControllerFindAll>>> = ({
		signal,
	}) => couponsControllerFindAll(signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof couponsControllerFindAll>>,
		TError,
		TData
	> & { queryKey: QueryKey };
};

export type CouponsControllerFindAllQueryResult = NonNullable<
	Awaited<ReturnType<typeof couponsControllerFindAll>>
>;
export type CouponsControllerFindAllQueryError = ErrorType<unknown>;

export function useCouponsControllerFindAll<
	TData = Awaited<ReturnType<typeof couponsControllerFindAll>>,
	TError = ErrorType<unknown>,
>(options: {
	query: Partial<
		UseQueryOptions<Awaited<ReturnType<typeof couponsControllerFindAll>>, TError, TData>
	> &
		Pick<
			DefinedInitialDataOptions<
				Awaited<ReturnType<typeof couponsControllerFindAll>>,
				TError,
				TData
			>,
			"initialData"
		>;
}): DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useCouponsControllerFindAll<
	TData = Awaited<ReturnType<typeof couponsControllerFindAll>>,
	TError = ErrorType<unknown>,
>(options?: {
	query?: Partial<
		UseQueryOptions<Awaited<ReturnType<typeof couponsControllerFindAll>>, TError, TData>
	> &
		Pick<
			UndefinedInitialDataOptions<
				Awaited<ReturnType<typeof couponsControllerFindAll>>,
				TError,
				TData
			>,
			"initialData"
		>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useCouponsControllerFindAll<
	TData = Awaited<ReturnType<typeof couponsControllerFindAll>>,
	TError = ErrorType<unknown>,
>(options?: {
	query?: Partial<
		UseQueryOptions<Awaited<ReturnType<typeof couponsControllerFindAll>>, TError, TData>
	>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey };

export function useCouponsControllerFindAll<
	TData = Awaited<ReturnType<typeof couponsControllerFindAll>>,
	TError = ErrorType<unknown>,
>(options?: {
	query?: Partial<
		UseQueryOptions<Awaited<ReturnType<typeof couponsControllerFindAll>>, TError, TData>
	>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
	const queryOptions = getCouponsControllerFindAllQueryOptions(options);

	const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

	query.queryKey = queryOptions.queryKey;

	return query;
}

export const couponsControllerFindOne = (id: string, signal?: AbortSignal) => {
	return authInstance<CouponsDto>({ url: `/api/coupons/${id}`, method: "GET", signal });
};

export const getCouponsControllerFindOneQueryKey = (id: string) => {
	return [`/api/coupons/${id}`] as const;
};

export const getCouponsControllerFindOneQueryOptions = <
	TData = Awaited<ReturnType<typeof couponsControllerFindOne>>,
	TError = ErrorType<unknown>,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof couponsControllerFindOne>>, TError, TData>
		>;
	},
) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getCouponsControllerFindOneQueryKey(id);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof couponsControllerFindOne>>> = ({
		signal,
	}) => couponsControllerFindOne(id, signal);

	return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof couponsControllerFindOne>>,
		TError,
		TData
	> & { queryKey: QueryKey };
};

export type CouponsControllerFindOneQueryResult = NonNullable<
	Awaited<ReturnType<typeof couponsControllerFindOne>>
>;
export type CouponsControllerFindOneQueryError = ErrorType<unknown>;

export function useCouponsControllerFindOne<
	TData = Awaited<ReturnType<typeof couponsControllerFindOne>>,
	TError = ErrorType<unknown>,
>(
	id: string,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof couponsControllerFindOne>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof couponsControllerFindOne>>,
					TError,
					TData
				>,
				"initialData"
			>;
	},
): DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useCouponsControllerFindOne<
	TData = Awaited<ReturnType<typeof couponsControllerFindOne>>,
	TError = ErrorType<unknown>,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof couponsControllerFindOne>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof couponsControllerFindOne>>,
					TError,
					TData
				>,
				"initialData"
			>;
	},
): UseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useCouponsControllerFindOne<
	TData = Awaited<ReturnType<typeof couponsControllerFindOne>>,
	TError = ErrorType<unknown>,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof couponsControllerFindOne>>, TError, TData>
		>;
	},
): UseQueryResult<TData, TError> & { queryKey: QueryKey };

export function useCouponsControllerFindOne<
	TData = Awaited<ReturnType<typeof couponsControllerFindOne>>,
	TError = ErrorType<unknown>,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof couponsControllerFindOne>>, TError, TData>
		>;
	},
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
	const queryOptions = getCouponsControllerFindOneQueryOptions(id, options);

	const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

	query.queryKey = queryOptions.queryKey;

	return query;
}

export const couponsControllerUpdate = (id: string, updateCouponsDto: UpdateCouponsDto) => {
	return authInstance<CouponsControllerUpdate200>({
		url: `/api/coupons/${id}`,
		method: "PATCH",
		headers: { "Content-Type": "application/json" },
		data: updateCouponsDto,
	});
};

export const getCouponsControllerUpdateMutationOptions = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof couponsControllerUpdate>>,
		TError,
		{ id: string; data: UpdateCouponsDto },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof couponsControllerUpdate>>,
	TError,
	{ id: string; data: UpdateCouponsDto },
	TContext
> => {
	const { mutation: mutationOptions } = options ?? {};

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof couponsControllerUpdate>>,
		{ id: string; data: UpdateCouponsDto }
	> = (props) => {
		const { id, data } = props ?? {};

		return couponsControllerUpdate(id, data);
	};

	return { mutationFn, ...mutationOptions };
};

export type CouponsControllerUpdateMutationResult = NonNullable<
	Awaited<ReturnType<typeof couponsControllerUpdate>>
>;
export type CouponsControllerUpdateMutationBody = UpdateCouponsDto;
export type CouponsControllerUpdateMutationError = ErrorType<unknown>;

export const useCouponsControllerUpdate = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof couponsControllerUpdate>>,
		TError,
		{ id: string; data: UpdateCouponsDto },
		TContext
	>;
}): UseMutationResult<
	Awaited<ReturnType<typeof couponsControllerUpdate>>,
	TError,
	{ id: string; data: UpdateCouponsDto },
	TContext
> => {
	const mutationOptions = getCouponsControllerUpdateMutationOptions(options);

	return useMutation(mutationOptions);
};
export const couponsControllerRemove = (id: string) => {
	return authInstance<void>({ url: `/api/coupons/${id}`, method: "DELETE" });
};

export const getCouponsControllerRemoveMutationOptions = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof couponsControllerRemove>>,
		TError,
		{ id: string },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof couponsControllerRemove>>,
	TError,
	{ id: string },
	TContext
> => {
	const { mutation: mutationOptions } = options ?? {};

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof couponsControllerRemove>>,
		{ id: string }
	> = (props) => {
		const { id } = props ?? {};

		return couponsControllerRemove(id);
	};

	return { mutationFn, ...mutationOptions };
};

export type CouponsControllerRemoveMutationResult = NonNullable<
	Awaited<ReturnType<typeof couponsControllerRemove>>
>;

export type CouponsControllerRemoveMutationError = ErrorType<unknown>;

export const useCouponsControllerRemove = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof couponsControllerRemove>>,
		TError,
		{ id: string },
		TContext
	>;
}): UseMutationResult<
	Awaited<ReturnType<typeof couponsControllerRemove>>,
	TError,
	{ id: string },
	TContext
> => {
	const mutationOptions = getCouponsControllerRemoveMutationOptions(options);

	return useMutation(mutationOptions);
};
