/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import type {
	BulkUpdateInventoryDto,
	CreateInventoryDto,
	InventoryControllerBulkUpdate200,
	InventoryControllerCreate201,
	InventoryControllerFindAll200,
	InventoryControllerFindAllParams,
	InventoryControllerFindByProductId200,
	InventoryControllerUpdate200,
	SuccessResponseDto,
	UpdateInventoryDto,
} from "./models";
import { authInstance } from "../../instances/authInstance";
import type { ErrorType } from "../../instances/authInstance";

/**
 * @summary Get all inventory entries
 */
export const inventoryControllerFindAll = (
	params?: InventoryControllerFindAllParams,
	signal?: AbortSignal,
) => {
	return authInstance<InventoryControllerFindAll200>({
		url: `/api/inventory`,
		method: "GET",
		params,
		signal,
	});
};

export const getInventoryControllerFindAllQueryKey = (
	params?: InventoryControllerFindAllParams,
) => {
	return [`/api/inventory`, ...(params ? [params] : [])] as const;
};

export const getInventoryControllerFindAllQueryOptions = <
	TData = Awaited<ReturnType<typeof inventoryControllerFindAll>>,
	TError = ErrorType<unknown>,
>(
	params?: InventoryControllerFindAllParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof inventoryControllerFindAll>>, TError, TData>
		>;
	},
) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getInventoryControllerFindAllQueryKey(params);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof inventoryControllerFindAll>>> = ({
		signal,
	}) => inventoryControllerFindAll(params, signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof inventoryControllerFindAll>>,
		TError,
		TData
	> & { queryKey: QueryKey };
};

export type InventoryControllerFindAllQueryResult = NonNullable<
	Awaited<ReturnType<typeof inventoryControllerFindAll>>
>;
export type InventoryControllerFindAllQueryError = ErrorType<unknown>;

export function useInventoryControllerFindAll<
	TData = Awaited<ReturnType<typeof inventoryControllerFindAll>>,
	TError = ErrorType<unknown>,
>(
	params: undefined | InventoryControllerFindAllParams,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof inventoryControllerFindAll>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof inventoryControllerFindAll>>,
					TError,
					TData
				>,
				"initialData"
			>;
	},
): DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useInventoryControllerFindAll<
	TData = Awaited<ReturnType<typeof inventoryControllerFindAll>>,
	TError = ErrorType<unknown>,
>(
	params?: InventoryControllerFindAllParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof inventoryControllerFindAll>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof inventoryControllerFindAll>>,
					TError,
					TData
				>,
				"initialData"
			>;
	},
): UseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useInventoryControllerFindAll<
	TData = Awaited<ReturnType<typeof inventoryControllerFindAll>>,
	TError = ErrorType<unknown>,
>(
	params?: InventoryControllerFindAllParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof inventoryControllerFindAll>>, TError, TData>
		>;
	},
): UseQueryResult<TData, TError> & { queryKey: QueryKey };
/**
 * @summary Get all inventory entries
 */

export function useInventoryControllerFindAll<
	TData = Awaited<ReturnType<typeof inventoryControllerFindAll>>,
	TError = ErrorType<unknown>,
>(
	params?: InventoryControllerFindAllParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof inventoryControllerFindAll>>, TError, TData>
		>;
	},
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
	const queryOptions = getInventoryControllerFindAllQueryOptions(params, options);

	const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

	query.queryKey = queryOptions.queryKey;

	return query;
}

/**
 * @summary Create or update inventory entry
 */
export const inventoryControllerCreate = (createInventoryDto: CreateInventoryDto) => {
	return authInstance<InventoryControllerCreate201>({
		url: `/api/inventory`,
		method: "POST",
		headers: { "Content-Type": "application/json" },
		data: createInventoryDto,
	});
};

export const getInventoryControllerCreateMutationOptions = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof inventoryControllerCreate>>,
		TError,
		{ data: CreateInventoryDto },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof inventoryControllerCreate>>,
	TError,
	{ data: CreateInventoryDto },
	TContext
> => {
	const { mutation: mutationOptions } = options ?? {};

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof inventoryControllerCreate>>,
		{ data: CreateInventoryDto }
	> = (props) => {
		const { data } = props ?? {};

		return inventoryControllerCreate(data);
	};

	return { mutationFn, ...mutationOptions };
};

export type InventoryControllerCreateMutationResult = NonNullable<
	Awaited<ReturnType<typeof inventoryControllerCreate>>
>;
export type InventoryControllerCreateMutationBody = CreateInventoryDto;
export type InventoryControllerCreateMutationError = ErrorType<unknown>;

/**
 * @summary Create or update inventory entry
 */
export const useInventoryControllerCreate = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof inventoryControllerCreate>>,
		TError,
		{ data: CreateInventoryDto },
		TContext
	>;
}): UseMutationResult<
	Awaited<ReturnType<typeof inventoryControllerCreate>>,
	TError,
	{ data: CreateInventoryDto },
	TContext
> => {
	const mutationOptions = getInventoryControllerCreateMutationOptions(options);

	return useMutation(mutationOptions);
};
/**
 * @summary Get inventory entry by product ID
 */
export const inventoryControllerFindByProductId = (productId: string, signal?: AbortSignal) => {
	return authInstance<InventoryControllerFindByProductId200>({
		url: `/api/inventory/product/${productId}`,
		method: "GET",
		signal,
	});
};

export const getInventoryControllerFindByProductIdQueryKey = (productId: string) => {
	return [`/api/inventory/product/${productId}`] as const;
};

export const getInventoryControllerFindByProductIdQueryOptions = <
	TData = Awaited<ReturnType<typeof inventoryControllerFindByProductId>>,
	TError = ErrorType<unknown>,
>(
	productId: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof inventoryControllerFindByProductId>>, TError, TData>
		>;
	},
) => {
	const { query: queryOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getInventoryControllerFindByProductIdQueryKey(productId);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof inventoryControllerFindByProductId>>> = ({
		signal,
	}) => inventoryControllerFindByProductId(productId, signal);

	return { queryKey, queryFn, enabled: !!productId, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof inventoryControllerFindByProductId>>,
		TError,
		TData
	> & { queryKey: QueryKey };
};

export type InventoryControllerFindByProductIdQueryResult = NonNullable<
	Awaited<ReturnType<typeof inventoryControllerFindByProductId>>
>;
export type InventoryControllerFindByProductIdQueryError = ErrorType<unknown>;

export function useInventoryControllerFindByProductId<
	TData = Awaited<ReturnType<typeof inventoryControllerFindByProductId>>,
	TError = ErrorType<unknown>,
>(
	productId: string,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof inventoryControllerFindByProductId>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof inventoryControllerFindByProductId>>,
					TError,
					TData
				>,
				"initialData"
			>;
	},
): DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useInventoryControllerFindByProductId<
	TData = Awaited<ReturnType<typeof inventoryControllerFindByProductId>>,
	TError = ErrorType<unknown>,
>(
	productId: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof inventoryControllerFindByProductId>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof inventoryControllerFindByProductId>>,
					TError,
					TData
				>,
				"initialData"
			>;
	},
): UseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useInventoryControllerFindByProductId<
	TData = Awaited<ReturnType<typeof inventoryControllerFindByProductId>>,
	TError = ErrorType<unknown>,
>(
	productId: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof inventoryControllerFindByProductId>>, TError, TData>
		>;
	},
): UseQueryResult<TData, TError> & { queryKey: QueryKey };
/**
 * @summary Get inventory entry by product ID
 */

export function useInventoryControllerFindByProductId<
	TData = Awaited<ReturnType<typeof inventoryControllerFindByProductId>>,
	TError = ErrorType<unknown>,
>(
	productId: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof inventoryControllerFindByProductId>>, TError, TData>
		>;
	},
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
	const queryOptions = getInventoryControllerFindByProductIdQueryOptions(productId, options);

	const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

	query.queryKey = queryOptions.queryKey;

	return query;
}

/**
 * @summary Update inventory entry
 */
export const inventoryControllerUpdate = (id: string, updateInventoryDto: UpdateInventoryDto) => {
	return authInstance<InventoryControllerUpdate200>({
		url: `/api/inventory/${id}`,
		method: "PUT",
		headers: { "Content-Type": "application/json" },
		data: updateInventoryDto,
	});
};

export const getInventoryControllerUpdateMutationOptions = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof inventoryControllerUpdate>>,
		TError,
		{ id: string; data: UpdateInventoryDto },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof inventoryControllerUpdate>>,
	TError,
	{ id: string; data: UpdateInventoryDto },
	TContext
> => {
	const { mutation: mutationOptions } = options ?? {};

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof inventoryControllerUpdate>>,
		{ id: string; data: UpdateInventoryDto }
	> = (props) => {
		const { id, data } = props ?? {};

		return inventoryControllerUpdate(id, data);
	};

	return { mutationFn, ...mutationOptions };
};

export type InventoryControllerUpdateMutationResult = NonNullable<
	Awaited<ReturnType<typeof inventoryControllerUpdate>>
>;
export type InventoryControllerUpdateMutationBody = UpdateInventoryDto;
export type InventoryControllerUpdateMutationError = ErrorType<unknown>;

/**
 * @summary Update inventory entry
 */
export const useInventoryControllerUpdate = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof inventoryControllerUpdate>>,
		TError,
		{ id: string; data: UpdateInventoryDto },
		TContext
	>;
}): UseMutationResult<
	Awaited<ReturnType<typeof inventoryControllerUpdate>>,
	TError,
	{ id: string; data: UpdateInventoryDto },
	TContext
> => {
	const mutationOptions = getInventoryControllerUpdateMutationOptions(options);

	return useMutation(mutationOptions);
};
/**
 * @summary Delete inventory entry
 */
export const inventoryControllerRemove = (id: string) => {
	return authInstance<SuccessResponseDto>({ url: `/api/inventory/${id}`, method: "DELETE" });
};

export const getInventoryControllerRemoveMutationOptions = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof inventoryControllerRemove>>,
		TError,
		{ id: string },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof inventoryControllerRemove>>,
	TError,
	{ id: string },
	TContext
> => {
	const { mutation: mutationOptions } = options ?? {};

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof inventoryControllerRemove>>,
		{ id: string }
	> = (props) => {
		const { id } = props ?? {};

		return inventoryControllerRemove(id);
	};

	return { mutationFn, ...mutationOptions };
};

export type InventoryControllerRemoveMutationResult = NonNullable<
	Awaited<ReturnType<typeof inventoryControllerRemove>>
>;

export type InventoryControllerRemoveMutationError = ErrorType<unknown>;

/**
 * @summary Delete inventory entry
 */
export const useInventoryControllerRemove = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof inventoryControllerRemove>>,
		TError,
		{ id: string },
		TContext
	>;
}): UseMutationResult<
	Awaited<ReturnType<typeof inventoryControllerRemove>>,
	TError,
	{ id: string },
	TContext
> => {
	const mutationOptions = getInventoryControllerRemoveMutationOptions(options);

	return useMutation(mutationOptions);
};
/**
 * @summary Bulk update inventory entries
 */
export const inventoryControllerBulkUpdate = (bulkUpdateInventoryDto: BulkUpdateInventoryDto) => {
	return authInstance<InventoryControllerBulkUpdate200 | void>({
		url: `/api/inventory/bulk`,
		method: "POST",
		headers: { "Content-Type": "application/json" },
		data: bulkUpdateInventoryDto,
	});
};

export const getInventoryControllerBulkUpdateMutationOptions = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof inventoryControllerBulkUpdate>>,
		TError,
		{ data: BulkUpdateInventoryDto },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof inventoryControllerBulkUpdate>>,
	TError,
	{ data: BulkUpdateInventoryDto },
	TContext
> => {
	const { mutation: mutationOptions } = options ?? {};

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof inventoryControllerBulkUpdate>>,
		{ data: BulkUpdateInventoryDto }
	> = (props) => {
		const { data } = props ?? {};

		return inventoryControllerBulkUpdate(data);
	};

	return { mutationFn, ...mutationOptions };
};

export type InventoryControllerBulkUpdateMutationResult = NonNullable<
	Awaited<ReturnType<typeof inventoryControllerBulkUpdate>>
>;
export type InventoryControllerBulkUpdateMutationBody = BulkUpdateInventoryDto;
export type InventoryControllerBulkUpdateMutationError = ErrorType<unknown>;

/**
 * @summary Bulk update inventory entries
 */
export const useInventoryControllerBulkUpdate = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof inventoryControllerBulkUpdate>>,
		TError,
		{ data: BulkUpdateInventoryDto },
		TContext
	>;
}): UseMutationResult<
	Awaited<ReturnType<typeof inventoryControllerBulkUpdate>>,
	TError,
	{ data: BulkUpdateInventoryDto },
	TContext
> => {
	const mutationOptions = getInventoryControllerBulkUpdateMutationOptions(options);

	return useMutation(mutationOptions);
};
