/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { authInstance } from "../../instances/authInstance";
import type { ErrorType } from "../../instances/authInstance";

// Inventory DTOs
export interface InventoryDto {
	id: string;
	productId: string;
	productName: string;
	quantity: number;
	lowStockThreshold: number;
	lastUpdated: string;
	unit: string;
	status: "available" | "partially_available" | "unavailable";
	user_id: string;
	createdAt: string;
	updatedAt: string;
}

export interface CreateInventoryDto {
	productId: string;
	quantity?: number;
	lowStockThreshold?: number;
	operation?: "add" | "subtract" | "set";
	amount?: number;
}

export interface UpdateInventoryDto {
	quantity?: number;
	lowStockThreshold?: number;
	operation?: "add" | "subtract" | "set";
	amount?: number;
}

export interface SuccessResponseDto {
	message: string;
}

// Response type for inventory list
export interface InventoryListResponse {
	data: InventoryDto[];
	message: string;
}

// API Functions
export const inventoryControllerFindAll = (signal?: AbortSignal) => {
	return authInstance<InventoryListResponse>({ url: `/api/inventory`, method: "GET", signal });
};

export const getInventoryControllerFindAllQueryKey = () => {
	return [`/api/inventory`] as const;
};

export const getInventoryControllerFindAllQueryOptions = <
	TData = Awaited<ReturnType<typeof inventoryControllerFindAll>>,
	TError = ErrorType<unknown>,
>(options?: {
	query?: Partial<
		UseQueryOptions<Awaited<ReturnType<typeof inventoryControllerFindAll>>, TError, TData>
	>;
}) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getInventoryControllerFindAllQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof inventoryControllerFindAll>>> = ({
		signal,
	}) => inventoryControllerFindAll(signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof inventoryControllerFindAll>>,
		TError,
		TData
	> & { queryKey: QueryKey };
};

export type InventoryControllerFindAllQueryResult = NonNullable<
	Awaited<ReturnType<typeof inventoryControllerFindAll>>
>;
export type InventoryControllerFindAllQueryError = ErrorType<unknown>;

export function useInventoryControllerFindAll<
	TData = Awaited<ReturnType<typeof inventoryControllerFindAll>>,
	TError = ErrorType<unknown>,
>(options: {
	query: Partial<
		UseQueryOptions<Awaited<ReturnType<typeof inventoryControllerFindAll>>, TError, TData>
	> &
		Pick<
			DefinedInitialDataOptions<
				Awaited<ReturnType<typeof inventoryControllerFindAll>>,
				TError,
				TData
			>,
			"initialData"
		>;
}): DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useInventoryControllerFindAll<
	TData = Awaited<ReturnType<typeof inventoryControllerFindAll>>,
	TError = ErrorType<unknown>,
>(options?: {
	query?: Partial<
		UseQueryOptions<Awaited<ReturnType<typeof inventoryControllerFindAll>>, TError, TData>
	> &
		Pick<
			UndefinedInitialDataOptions<
				Awaited<ReturnType<typeof inventoryControllerFindAll>>,
				TError,
				TData
			>,
			"initialData"
		>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useInventoryControllerFindAll<
	TData = Awaited<ReturnType<typeof inventoryControllerFindAll>>,
	TError = ErrorType<unknown>,
>(options?: {
	query?: Partial<
		UseQueryOptions<Awaited<ReturnType<typeof inventoryControllerFindAll>>, TError, TData>
	>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey };

export function useInventoryControllerFindAll<
	TData = Awaited<ReturnType<typeof inventoryControllerFindAll>>,
	TError = ErrorType<unknown>,
>(options?: {
	query?: Partial<
		UseQueryOptions<Awaited<ReturnType<typeof inventoryControllerFindAll>>, TError, TData>
	>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
	const queryOptions = getInventoryControllerFindAllQueryOptions(options);

	const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

	query.queryKey = queryOptions.queryKey;

	return query;
}

export const inventoryControllerFindByProductId = (productId: string, signal?: AbortSignal) => {
	return authInstance<InventoryDto>({
		url: `/api/inventory/product/${productId}`,
		method: "GET",
		signal,
	});
};

export const getInventoryControllerFindByProductIdQueryKey = (productId: string) => {
	return [`/api/inventory/product/${productId}`] as const;
};

export const inventoryControllerCreate = (createInventoryDto: CreateInventoryDto) => {
	return authInstance<InventoryDto>({
		url: `/api/inventory`,
		method: "POST",
		headers: { "Content-Type": "application/json" },
		data: createInventoryDto,
	});
};

export const getInventoryControllerCreateMutationOptions = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof inventoryControllerCreate>>,
		TError,
		{ data: CreateInventoryDto },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof inventoryControllerCreate>>,
	TError,
	{ data: CreateInventoryDto },
	TContext
> => {
	const { mutation: mutationOptions } = options ?? {};

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof inventoryControllerCreate>>,
		{ data: CreateInventoryDto }
	> = (props) => {
		const { data } = props ?? {};

		return inventoryControllerCreate(data);
	};

	return { mutationFn, ...mutationOptions };
};

export type InventoryControllerCreateMutationResult = NonNullable<
	Awaited<ReturnType<typeof inventoryControllerCreate>>
>;
export type InventoryControllerCreateMutationBody = CreateInventoryDto;
export type InventoryControllerCreateMutationError = ErrorType<unknown>;

export const useInventoryControllerCreate = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof inventoryControllerCreate>>,
		TError,
		{ data: CreateInventoryDto },
		TContext
	>;
}): UseMutationResult<
	Awaited<ReturnType<typeof inventoryControllerCreate>>,
	TError,
	{ data: CreateInventoryDto },
	TContext
> => {
	const mutationOptions = getInventoryControllerCreateMutationOptions(options);

	return useMutation(mutationOptions);
};

export const inventoryControllerUpdate = (id: string, updateInventoryDto: UpdateInventoryDto) => {
	return authInstance<InventoryDto>({
		url: `/api/inventory/${id}`,
		method: "PUT",
		headers: { "Content-Type": "application/json" },
		data: updateInventoryDto,
	});
};

export const getInventoryControllerUpdateMutationOptions = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof inventoryControllerUpdate>>,
		TError,
		{ id: string; data: UpdateInventoryDto },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof inventoryControllerUpdate>>,
	TError,
	{ id: string; data: UpdateInventoryDto },
	TContext
> => {
	const { mutation: mutationOptions } = options ?? {};

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof inventoryControllerUpdate>>,
		{ id: string; data: UpdateInventoryDto }
	> = (props) => {
		const { id, data } = props ?? {};

		return inventoryControllerUpdate(id, data);
	};

	return { mutationFn, ...mutationOptions };
};

export type InventoryControllerUpdateMutationResult = NonNullable<
	Awaited<ReturnType<typeof inventoryControllerUpdate>>
>;
export type InventoryControllerUpdateMutationBody = UpdateInventoryDto;
export type InventoryControllerUpdateMutationError = ErrorType<unknown>;

export const useInventoryControllerUpdate = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof inventoryControllerUpdate>>,
		TError,
		{ id: string; data: UpdateInventoryDto },
		TContext
	>;
}): UseMutationResult<
	Awaited<ReturnType<typeof inventoryControllerUpdate>>,
	TError,
	{ id: string; data: UpdateInventoryDto },
	TContext
> => {
	const mutationOptions = getInventoryControllerUpdateMutationOptions(options);

	return useMutation(mutationOptions);
};

export const inventoryControllerRemove = (id: string) => {
	return authInstance<SuccessResponseDto>({ url: `/api/inventory/${id}`, method: "DELETE" });
};

export const getInventoryControllerRemoveMutationOptions = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof inventoryControllerRemove>>,
		TError,
		{ id: string },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof inventoryControllerRemove>>,
	TError,
	{ id: string },
	TContext
> => {
	const { mutation: mutationOptions } = options ?? {};

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof inventoryControllerRemove>>,
		{ id: string }
	> = (props) => {
		const { id } = props ?? {};

		return inventoryControllerRemove(id);
	};

	return { mutationFn, ...mutationOptions };
};

export type InventoryControllerRemoveMutationResult = NonNullable<
	Awaited<ReturnType<typeof inventoryControllerRemove>>
>;

export type InventoryControllerRemoveMutationError = ErrorType<unknown>;

export const useInventoryControllerRemove = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof inventoryControllerRemove>>,
		TError,
		{ id: string },
		TContext
	>;
}): UseMutationResult<
	Awaited<ReturnType<typeof inventoryControllerRemove>>,
	TError,
	{ id: string },
	TContext
> => {
	const mutationOptions = getInventoryControllerRemoveMutationOptions(options);

	return useMutation(mutationOptions);
};
