/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { authInstance } from "../../instances/authInstance";
import type { ErrorType } from "../../instances/authInstance";

/**
 * @summary Track shipment by AWB number
 */
export const shiprocketControllerTrackByAwb = (awb: string, signal?: AbortSignal) => {
	return authInstance<void>({ url: `/api/shiprocket/track/awb/${awb}`, method: "GET", signal });
};

export const getShiprocketControllerTrackByAwbQueryKey = (awb: string) => {
	return [`/api/shiprocket/track/awb/${awb}`] as const;
};

export const getShiprocketControllerTrackByAwbQueryOptions = <
	TData = Awaited<ReturnType<typeof shiprocketControllerTrackByAwb>>,
	TError = ErrorType<void>,
>(
	awb: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof shiprocketControllerTrackByAwb>>, TError, TData>
		>;
	},
) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getShiprocketControllerTrackByAwbQueryKey(awb);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof shiprocketControllerTrackByAwb>>> = ({
		signal,
	}) => shiprocketControllerTrackByAwb(awb, signal);

	return { queryKey, queryFn, enabled: !!awb, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof shiprocketControllerTrackByAwb>>,
		TError,
		TData
	> & { queryKey: QueryKey };
};

export type ShiprocketControllerTrackByAwbQueryResult = NonNullable<
	Awaited<ReturnType<typeof shiprocketControllerTrackByAwb>>
>;
export type ShiprocketControllerTrackByAwbQueryError = ErrorType<void>;

export function useShiprocketControllerTrackByAwb<
	TData = Awaited<ReturnType<typeof shiprocketControllerTrackByAwb>>,
	TError = ErrorType<void>,
>(
	awb: string,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof shiprocketControllerTrackByAwb>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof shiprocketControllerTrackByAwb>>,
					TError,
					TData
				>,
				"initialData"
			>;
	},
): DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useShiprocketControllerTrackByAwb<
	TData = Awaited<ReturnType<typeof shiprocketControllerTrackByAwb>>,
	TError = ErrorType<void>,
>(
	awb: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof shiprocketControllerTrackByAwb>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof shiprocketControllerTrackByAwb>>,
					TError,
					TData
				>,
				"initialData"
			>;
	},
): UseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useShiprocketControllerTrackByAwb<
	TData = Awaited<ReturnType<typeof shiprocketControllerTrackByAwb>>,
	TError = ErrorType<void>,
>(
	awb: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof shiprocketControllerTrackByAwb>>, TError, TData>
		>;
	},
): UseQueryResult<TData, TError> & { queryKey: QueryKey };
/**
 * @summary Track shipment by AWB number
 */

export function useShiprocketControllerTrackByAwb<
	TData = Awaited<ReturnType<typeof shiprocketControllerTrackByAwb>>,
	TError = ErrorType<void>,
>(
	awb: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof shiprocketControllerTrackByAwb>>, TError, TData>
		>;
	},
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
	const queryOptions = getShiprocketControllerTrackByAwbQueryOptions(awb, options);

	const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

	query.queryKey = queryOptions.queryKey;

	return query;
}

/**
 * @summary Track shipment by Shiprocket shipment ID
 */
export const shiprocketControllerTrackByShipmentId = (shipmentId: string, signal?: AbortSignal) => {
	return authInstance<void>({
		url: `/api/shiprocket/track/shipment/${shipmentId}`,
		method: "GET",
		signal,
	});
};

export const getShiprocketControllerTrackByShipmentIdQueryKey = (shipmentId: string) => {
	return [`/api/shiprocket/track/shipment/${shipmentId}`] as const;
};

export const getShiprocketControllerTrackByShipmentIdQueryOptions = <
	TData = Awaited<ReturnType<typeof shiprocketControllerTrackByShipmentId>>,
	TError = ErrorType<void>,
>(
	shipmentId: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof shiprocketControllerTrackByShipmentId>>,
				TError,
				TData
			>
		>;
	},
) => {
	const { query: queryOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getShiprocketControllerTrackByShipmentIdQueryKey(shipmentId);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof shiprocketControllerTrackByShipmentId>>
	> = ({ signal }) => shiprocketControllerTrackByShipmentId(shipmentId, signal);

	return { queryKey, queryFn, enabled: !!shipmentId, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof shiprocketControllerTrackByShipmentId>>,
		TError,
		TData
	> & { queryKey: QueryKey };
};

export type ShiprocketControllerTrackByShipmentIdQueryResult = NonNullable<
	Awaited<ReturnType<typeof shiprocketControllerTrackByShipmentId>>
>;
export type ShiprocketControllerTrackByShipmentIdQueryError = ErrorType<void>;

export function useShiprocketControllerTrackByShipmentId<
	TData = Awaited<ReturnType<typeof shiprocketControllerTrackByShipmentId>>,
	TError = ErrorType<void>,
>(
	shipmentId: string,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof shiprocketControllerTrackByShipmentId>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof shiprocketControllerTrackByShipmentId>>,
					TError,
					TData
				>,
				"initialData"
			>;
	},
): DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useShiprocketControllerTrackByShipmentId<
	TData = Awaited<ReturnType<typeof shiprocketControllerTrackByShipmentId>>,
	TError = ErrorType<void>,
>(
	shipmentId: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof shiprocketControllerTrackByShipmentId>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof shiprocketControllerTrackByShipmentId>>,
					TError,
					TData
				>,
				"initialData"
			>;
	},
): UseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useShiprocketControllerTrackByShipmentId<
	TData = Awaited<ReturnType<typeof shiprocketControllerTrackByShipmentId>>,
	TError = ErrorType<void>,
>(
	shipmentId: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof shiprocketControllerTrackByShipmentId>>,
				TError,
				TData
			>
		>;
	},
): UseQueryResult<TData, TError> & { queryKey: QueryKey };
/**
 * @summary Track shipment by Shiprocket shipment ID
 */

export function useShiprocketControllerTrackByShipmentId<
	TData = Awaited<ReturnType<typeof shiprocketControllerTrackByShipmentId>>,
	TError = ErrorType<void>,
>(
	shipmentId: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof shiprocketControllerTrackByShipmentId>>,
				TError,
				TData
			>
		>;
	},
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
	const queryOptions = getShiprocketControllerTrackByShipmentIdQueryOptions(shipmentId, options);

	const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

	query.queryKey = queryOptions.queryKey;

	return query;
}
