/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import type {
	CheckoutInvoiceCreateDto,
	CreateStoreDto,
	InvoiceDto,
	StoreControllerGetStoreParams,
	StoreControllerSearchProductsParams,
	UserWithProducts,
} from "./models";
import { authInstance } from "../../instances/authInstance";
import type { ErrorType } from "../../instances/authInstance";

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export const storeControllerCreateUpdateStore = (createStoreDto: CreateStoreDto) => {
	return authInstance<void>({
		url: `/api/store/create-update-store`,
		method: "POST",
		headers: { "Content-Type": "application/json" },
		data: createStoreDto,
	});
};

export const getStoreControllerCreateUpdateStoreMutationOptions = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof storeControllerCreateUpdateStore>>,
		TError,
		{ data: CreateStoreDto },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof storeControllerCreateUpdateStore>>,
	TError,
	{ data: CreateStoreDto },
	TContext
> => {
	const { mutation: mutationOptions } = options ?? {};

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof storeControllerCreateUpdateStore>>,
		{ data: CreateStoreDto }
	> = (props) => {
		const { data } = props ?? {};

		return storeControllerCreateUpdateStore(data);
	};

	return { mutationFn, ...mutationOptions };
};

export type StoreControllerCreateUpdateStoreMutationResult = NonNullable<
	Awaited<ReturnType<typeof storeControllerCreateUpdateStore>>
>;
export type StoreControllerCreateUpdateStoreMutationBody = CreateStoreDto;
export type StoreControllerCreateUpdateStoreMutationError = ErrorType<unknown>;

export const useStoreControllerCreateUpdateStore = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof storeControllerCreateUpdateStore>>,
		TError,
		{ data: CreateStoreDto },
		TContext
	>;
}): UseMutationResult<
	Awaited<ReturnType<typeof storeControllerCreateUpdateStore>>,
	TError,
	{ data: CreateStoreDto },
	TContext
> => {
	const mutationOptions = getStoreControllerCreateUpdateStoreMutationOptions(options);

	return useMutation(mutationOptions);
};
export const storeControllerCreateCheckoutInvoice = (
	checkoutInvoiceCreateDto: CheckoutInvoiceCreateDto,
) => {
	return authInstance<InvoiceDto>({
		url: `/api/store/checkout`,
		method: "POST",
		headers: { "Content-Type": "application/json" },
		data: checkoutInvoiceCreateDto,
	});
};

export const getStoreControllerCreateCheckoutInvoiceMutationOptions = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof storeControllerCreateCheckoutInvoice>>,
		TError,
		{ data: CheckoutInvoiceCreateDto },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof storeControllerCreateCheckoutInvoice>>,
	TError,
	{ data: CheckoutInvoiceCreateDto },
	TContext
> => {
	const { mutation: mutationOptions } = options ?? {};

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof storeControllerCreateCheckoutInvoice>>,
		{ data: CheckoutInvoiceCreateDto }
	> = (props) => {
		const { data } = props ?? {};

		return storeControllerCreateCheckoutInvoice(data);
	};

	return { mutationFn, ...mutationOptions };
};

export type StoreControllerCreateCheckoutInvoiceMutationResult = NonNullable<
	Awaited<ReturnType<typeof storeControllerCreateCheckoutInvoice>>
>;
export type StoreControllerCreateCheckoutInvoiceMutationBody = CheckoutInvoiceCreateDto;
export type StoreControllerCreateCheckoutInvoiceMutationError = ErrorType<unknown>;

export const useStoreControllerCreateCheckoutInvoice = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof storeControllerCreateCheckoutInvoice>>,
		TError,
		{ data: CheckoutInvoiceCreateDto },
		TContext
	>;
}): UseMutationResult<
	Awaited<ReturnType<typeof storeControllerCreateCheckoutInvoice>>,
	TError,
	{ data: CheckoutInvoiceCreateDto },
	TContext
> => {
	const mutationOptions = getStoreControllerCreateCheckoutInvoiceMutationOptions(options);

	return useMutation(mutationOptions);
};
export const storeControllerGetStore = (
	params: StoreControllerGetStoreParams,
	signal?: AbortSignal,
) => {
	return authInstance<UserWithProducts>({ url: `/api/store`, method: "GET", params, signal });
};

export const getStoreControllerGetStoreQueryKey = (params: StoreControllerGetStoreParams) => {
	return [`/api/store`, ...(params ? [params] : [])] as const;
};

export const getStoreControllerGetStoreQueryOptions = <
	TData = Awaited<ReturnType<typeof storeControllerGetStore>>,
	TError = ErrorType<unknown>,
>(
	params: StoreControllerGetStoreParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetStore>>, TError, TData>
		>;
	},
) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getStoreControllerGetStoreQueryKey(params);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof storeControllerGetStore>>> = ({
		signal,
	}) => storeControllerGetStore(params, signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof storeControllerGetStore>>,
		TError,
		TData
	> & { queryKey: QueryKey };
};

export type StoreControllerGetStoreQueryResult = NonNullable<
	Awaited<ReturnType<typeof storeControllerGetStore>>
>;
export type StoreControllerGetStoreQueryError = ErrorType<unknown>;

export function useStoreControllerGetStore<
	TData = Awaited<ReturnType<typeof storeControllerGetStore>>,
	TError = ErrorType<unknown>,
>(
	params: StoreControllerGetStoreParams,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetStore>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof storeControllerGetStore>>,
					TError,
					TData
				>,
				"initialData"
			>;
	},
): DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useStoreControllerGetStore<
	TData = Awaited<ReturnType<typeof storeControllerGetStore>>,
	TError = ErrorType<unknown>,
>(
	params: StoreControllerGetStoreParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetStore>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof storeControllerGetStore>>,
					TError,
					TData
				>,
				"initialData"
			>;
	},
): UseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useStoreControllerGetStore<
	TData = Awaited<ReturnType<typeof storeControllerGetStore>>,
	TError = ErrorType<unknown>,
>(
	params: StoreControllerGetStoreParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetStore>>, TError, TData>
		>;
	},
): UseQueryResult<TData, TError> & { queryKey: QueryKey };

export function useStoreControllerGetStore<
	TData = Awaited<ReturnType<typeof storeControllerGetStore>>,
	TError = ErrorType<unknown>,
>(
	params: StoreControllerGetStoreParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetStore>>, TError, TData>
		>;
	},
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
	const queryOptions = getStoreControllerGetStoreQueryOptions(params, options);

	const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

	query.queryKey = queryOptions.queryKey;

	return query;
}

export const storeControllerSearchProducts = (
	params: StoreControllerSearchProductsParams,
	signal?: AbortSignal,
) => {
	return authInstance<UserWithProducts[]>({
		url: `/api/store/search`,
		method: "GET",
		params,
		signal,
	});
};

export const getStoreControllerSearchProductsQueryKey = (
	params: StoreControllerSearchProductsParams,
) => {
	return [`/api/store/search`, ...(params ? [params] : [])] as const;
};

export const getStoreControllerSearchProductsQueryOptions = <
	TData = Awaited<ReturnType<typeof storeControllerSearchProducts>>,
	TError = ErrorType<unknown>,
>(
	params: StoreControllerSearchProductsParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof storeControllerSearchProducts>>, TError, TData>
		>;
	},
) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getStoreControllerSearchProductsQueryKey(params);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof storeControllerSearchProducts>>> = ({
		signal,
	}) => storeControllerSearchProducts(params, signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof storeControllerSearchProducts>>,
		TError,
		TData
	> & { queryKey: QueryKey };
};

export type StoreControllerSearchProductsQueryResult = NonNullable<
	Awaited<ReturnType<typeof storeControllerSearchProducts>>
>;
export type StoreControllerSearchProductsQueryError = ErrorType<unknown>;

export function useStoreControllerSearchProducts<
	TData = Awaited<ReturnType<typeof storeControllerSearchProducts>>,
	TError = ErrorType<unknown>,
>(
	params: StoreControllerSearchProductsParams,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof storeControllerSearchProducts>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof storeControllerSearchProducts>>,
					TError,
					TData
				>,
				"initialData"
			>;
	},
): DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useStoreControllerSearchProducts<
	TData = Awaited<ReturnType<typeof storeControllerSearchProducts>>,
	TError = ErrorType<unknown>,
>(
	params: StoreControllerSearchProductsParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof storeControllerSearchProducts>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof storeControllerSearchProducts>>,
					TError,
					TData
				>,
				"initialData"
			>;
	},
): UseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useStoreControllerSearchProducts<
	TData = Awaited<ReturnType<typeof storeControllerSearchProducts>>,
	TError = ErrorType<unknown>,
>(
	params: StoreControllerSearchProductsParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof storeControllerSearchProducts>>, TError, TData>
		>;
	},
): UseQueryResult<TData, TError> & { queryKey: QueryKey };

export function useStoreControllerSearchProducts<
	TData = Awaited<ReturnType<typeof storeControllerSearchProducts>>,
	TError = ErrorType<unknown>,
>(
	params: StoreControllerSearchProductsParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof storeControllerSearchProducts>>, TError, TData>
		>;
	},
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
	const queryOptions = getStoreControllerSearchProductsQueryOptions(params, options);

	const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

	query.queryKey = queryOptions.queryKey;

	return query;
}
