/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import type {
	AdminUsersListDto,
	CreateUserCompany,
	DashboardCount,
	ErrorMessageDto,
	ForgotPasswordDto,
	LoginSuccessDto,
	LoginUserDto,
	ResetPasswordTokenDto,
	UpdateCurrencyCompanyDto,
	UpdateUserCompany,
	UserControllerBlockUser200,
	UserControllerUpdateCurrencyCompany201,
	UserControllerUpdateUser201,
} from "./models";
import { authInstance } from "../../instances/authInstance";
import type { ErrorType } from "../../instances/authInstance";

export const userControllerCreateUser = (createUserCompany: CreateUserCompany) => {
	return authInstance<LoginSuccessDto>({
		url: `/api/user/create`,
		method: "POST",
		headers: { "Content-Type": "application/json" },
		data: createUserCompany,
	});
};

export const getUserControllerCreateUserMutationOptions = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof userControllerCreateUser>>,
		TError,
		{ data: CreateUserCompany },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof userControllerCreateUser>>,
	TError,
	{ data: CreateUserCompany },
	TContext
> => {
	const { mutation: mutationOptions } = options ?? {};

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof userControllerCreateUser>>,
		{ data: CreateUserCompany }
	> = (props) => {
		const { data } = props ?? {};

		return userControllerCreateUser(data);
	};

	return { mutationFn, ...mutationOptions };
};

export type UserControllerCreateUserMutationResult = NonNullable<
	Awaited<ReturnType<typeof userControllerCreateUser>>
>;
export type UserControllerCreateUserMutationBody = CreateUserCompany;
export type UserControllerCreateUserMutationError = ErrorType<unknown>;

export const useUserControllerCreateUser = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof userControllerCreateUser>>,
		TError,
		{ data: CreateUserCompany },
		TContext
	>;
}): UseMutationResult<
	Awaited<ReturnType<typeof userControllerCreateUser>>,
	TError,
	{ data: CreateUserCompany },
	TContext
> => {
	const mutationOptions = getUserControllerCreateUserMutationOptions(options);

	return useMutation(mutationOptions);
};
export const userControllerLoginUser = (loginUserDto: LoginUserDto) => {
	return authInstance<LoginSuccessDto>({
		url: `/api/user/login`,
		method: "POST",
		headers: { "Content-Type": "application/json" },
		data: loginUserDto,
	});
};

export const getUserControllerLoginUserMutationOptions = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof userControllerLoginUser>>,
		TError,
		{ data: LoginUserDto },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof userControllerLoginUser>>,
	TError,
	{ data: LoginUserDto },
	TContext
> => {
	const { mutation: mutationOptions } = options ?? {};

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof userControllerLoginUser>>,
		{ data: LoginUserDto }
	> = (props) => {
		const { data } = props ?? {};

		return userControllerLoginUser(data);
	};

	return { mutationFn, ...mutationOptions };
};

export type UserControllerLoginUserMutationResult = NonNullable<
	Awaited<ReturnType<typeof userControllerLoginUser>>
>;
export type UserControllerLoginUserMutationBody = LoginUserDto;
export type UserControllerLoginUserMutationError = ErrorType<unknown>;

export const useUserControllerLoginUser = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof userControllerLoginUser>>,
		TError,
		{ data: LoginUserDto },
		TContext
	>;
}): UseMutationResult<
	Awaited<ReturnType<typeof userControllerLoginUser>>,
	TError,
	{ data: LoginUserDto },
	TContext
> => {
	const mutationOptions = getUserControllerLoginUserMutationOptions(options);

	return useMutation(mutationOptions);
};
export const userControllerForgotPassword = (forgotPasswordDto: ForgotPasswordDto) => {
	return authInstance<ErrorMessageDto | void>({
		url: `/api/user/forgot-password`,
		method: "POST",
		headers: { "Content-Type": "application/json" },
		data: forgotPasswordDto,
	});
};

export const getUserControllerForgotPasswordMutationOptions = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof userControllerForgotPassword>>,
		TError,
		{ data: ForgotPasswordDto },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof userControllerForgotPassword>>,
	TError,
	{ data: ForgotPasswordDto },
	TContext
> => {
	const { mutation: mutationOptions } = options ?? {};

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof userControllerForgotPassword>>,
		{ data: ForgotPasswordDto }
	> = (props) => {
		const { data } = props ?? {};

		return userControllerForgotPassword(data);
	};

	return { mutationFn, ...mutationOptions };
};

export type UserControllerForgotPasswordMutationResult = NonNullable<
	Awaited<ReturnType<typeof userControllerForgotPassword>>
>;
export type UserControllerForgotPasswordMutationBody = ForgotPasswordDto;
export type UserControllerForgotPasswordMutationError = ErrorType<unknown>;

export const useUserControllerForgotPassword = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof userControllerForgotPassword>>,
		TError,
		{ data: ForgotPasswordDto },
		TContext
	>;
}): UseMutationResult<
	Awaited<ReturnType<typeof userControllerForgotPassword>>,
	TError,
	{ data: ForgotPasswordDto },
	TContext
> => {
	const mutationOptions = getUserControllerForgotPasswordMutationOptions(options);

	return useMutation(mutationOptions);
};
export const userControllerResetPassword = (resetPasswordTokenDto: ResetPasswordTokenDto) => {
	return authInstance<ErrorMessageDto | void>({
		url: `/api/user/reset-password`,
		method: "POST",
		headers: { "Content-Type": "application/json" },
		data: resetPasswordTokenDto,
	});
};

export const getUserControllerResetPasswordMutationOptions = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof userControllerResetPassword>>,
		TError,
		{ data: ResetPasswordTokenDto },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof userControllerResetPassword>>,
	TError,
	{ data: ResetPasswordTokenDto },
	TContext
> => {
	const { mutation: mutationOptions } = options ?? {};

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof userControllerResetPassword>>,
		{ data: ResetPasswordTokenDto }
	> = (props) => {
		const { data } = props ?? {};

		return userControllerResetPassword(data);
	};

	return { mutationFn, ...mutationOptions };
};

export type UserControllerResetPasswordMutationResult = NonNullable<
	Awaited<ReturnType<typeof userControllerResetPassword>>
>;
export type UserControllerResetPasswordMutationBody = ResetPasswordTokenDto;
export type UserControllerResetPasswordMutationError = ErrorType<unknown>;

export const useUserControllerResetPassword = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof userControllerResetPassword>>,
		TError,
		{ data: ResetPasswordTokenDto },
		TContext
	>;
}): UseMutationResult<
	Awaited<ReturnType<typeof userControllerResetPassword>>,
	TError,
	{ data: ResetPasswordTokenDto },
	TContext
> => {
	const mutationOptions = getUserControllerResetPasswordMutationOptions(options);

	return useMutation(mutationOptions);
};
export const userControllerUpdateCurrencyCompany = (
	updateCurrencyCompanyDto: UpdateCurrencyCompanyDto,
) => {
	return authInstance<UserControllerUpdateCurrencyCompany201>({
		url: `/api/user/update-currency-company`,
		method: "POST",
		headers: { "Content-Type": "application/json" },
		data: updateCurrencyCompanyDto,
	});
};

export const getUserControllerUpdateCurrencyCompanyMutationOptions = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof userControllerUpdateCurrencyCompany>>,
		TError,
		{ data: UpdateCurrencyCompanyDto },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof userControllerUpdateCurrencyCompany>>,
	TError,
	{ data: UpdateCurrencyCompanyDto },
	TContext
> => {
	const { mutation: mutationOptions } = options ?? {};

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof userControllerUpdateCurrencyCompany>>,
		{ data: UpdateCurrencyCompanyDto }
	> = (props) => {
		const { data } = props ?? {};

		return userControllerUpdateCurrencyCompany(data);
	};

	return { mutationFn, ...mutationOptions };
};

export type UserControllerUpdateCurrencyCompanyMutationResult = NonNullable<
	Awaited<ReturnType<typeof userControllerUpdateCurrencyCompany>>
>;
export type UserControllerUpdateCurrencyCompanyMutationBody = UpdateCurrencyCompanyDto;
export type UserControllerUpdateCurrencyCompanyMutationError = ErrorType<unknown>;

export const useUserControllerUpdateCurrencyCompany = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof userControllerUpdateCurrencyCompany>>,
		TError,
		{ data: UpdateCurrencyCompanyDto },
		TContext
	>;
}): UseMutationResult<
	Awaited<ReturnType<typeof userControllerUpdateCurrencyCompany>>,
	TError,
	{ data: UpdateCurrencyCompanyDto },
	TContext
> => {
	const mutationOptions = getUserControllerUpdateCurrencyCompanyMutationOptions(options);

	return useMutation(mutationOptions);
};
export const userControllerUpdateUser = (id: string, updateUserCompany: UpdateUserCompany) => {
	return authInstance<void | UserControllerUpdateUser201>({
		url: `/api/user/updateUser/${id}`,
		method: "PUT",
		headers: { "Content-Type": "application/json" },
		data: updateUserCompany,
	});
};

export const getUserControllerUpdateUserMutationOptions = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof userControllerUpdateUser>>,
		TError,
		{ id: string; data: UpdateUserCompany },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof userControllerUpdateUser>>,
	TError,
	{ id: string; data: UpdateUserCompany },
	TContext
> => {
	const { mutation: mutationOptions } = options ?? {};

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof userControllerUpdateUser>>,
		{ id: string; data: UpdateUserCompany }
	> = (props) => {
		const { id, data } = props ?? {};

		return userControllerUpdateUser(id, data);
	};

	return { mutationFn, ...mutationOptions };
};

export type UserControllerUpdateUserMutationResult = NonNullable<
	Awaited<ReturnType<typeof userControllerUpdateUser>>
>;
export type UserControllerUpdateUserMutationBody = UpdateUserCompany;
export type UserControllerUpdateUserMutationError = ErrorType<unknown>;

export const useUserControllerUpdateUser = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof userControllerUpdateUser>>,
		TError,
		{ id: string; data: UpdateUserCompany },
		TContext
	>;
}): UseMutationResult<
	Awaited<ReturnType<typeof userControllerUpdateUser>>,
	TError,
	{ id: string; data: UpdateUserCompany },
	TContext
> => {
	const mutationOptions = getUserControllerUpdateUserMutationOptions(options);

	return useMutation(mutationOptions);
};
export const userControllerUserCount = (signal?: AbortSignal) => {
	return authInstance<number>({ url: `/api/user/userCount`, method: "GET", signal });
};

export const getUserControllerUserCountQueryKey = () => {
	return [`/api/user/userCount`] as const;
};

export const getUserControllerUserCountQueryOptions = <
	TData = Awaited<ReturnType<typeof userControllerUserCount>>,
	TError = ErrorType<unknown>,
>(options?: {
	query?: Partial<
		UseQueryOptions<Awaited<ReturnType<typeof userControllerUserCount>>, TError, TData>
	>;
}) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getUserControllerUserCountQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof userControllerUserCount>>> = ({
		signal,
	}) => userControllerUserCount(signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof userControllerUserCount>>,
		TError,
		TData
	> & { queryKey: QueryKey };
};

export type UserControllerUserCountQueryResult = NonNullable<
	Awaited<ReturnType<typeof userControllerUserCount>>
>;
export type UserControllerUserCountQueryError = ErrorType<unknown>;

export function useUserControllerUserCount<
	TData = Awaited<ReturnType<typeof userControllerUserCount>>,
	TError = ErrorType<unknown>,
>(options: {
	query: Partial<
		UseQueryOptions<Awaited<ReturnType<typeof userControllerUserCount>>, TError, TData>
	> &
		Pick<
			DefinedInitialDataOptions<Awaited<ReturnType<typeof userControllerUserCount>>, TError, TData>,
			"initialData"
		>;
}): DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useUserControllerUserCount<
	TData = Awaited<ReturnType<typeof userControllerUserCount>>,
	TError = ErrorType<unknown>,
>(options?: {
	query?: Partial<
		UseQueryOptions<Awaited<ReturnType<typeof userControllerUserCount>>, TError, TData>
	> &
		Pick<
			UndefinedInitialDataOptions<
				Awaited<ReturnType<typeof userControllerUserCount>>,
				TError,
				TData
			>,
			"initialData"
		>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useUserControllerUserCount<
	TData = Awaited<ReturnType<typeof userControllerUserCount>>,
	TError = ErrorType<unknown>,
>(options?: {
	query?: Partial<
		UseQueryOptions<Awaited<ReturnType<typeof userControllerUserCount>>, TError, TData>
	>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey };

export function useUserControllerUserCount<
	TData = Awaited<ReturnType<typeof userControllerUserCount>>,
	TError = ErrorType<unknown>,
>(options?: {
	query?: Partial<
		UseQueryOptions<Awaited<ReturnType<typeof userControllerUserCount>>, TError, TData>
	>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
	const queryOptions = getUserControllerUserCountQueryOptions(options);

	const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

	query.queryKey = queryOptions.queryKey;

	return query;
}

export const userControllerGetUsersList = (signal?: AbortSignal) => {
	return authInstance<AdminUsersListDto[]>({
		url: `/api/user/getUsersList`,
		method: "GET",
		signal,
	});
};

export const getUserControllerGetUsersListQueryKey = () => {
	return [`/api/user/getUsersList`] as const;
};

export const getUserControllerGetUsersListQueryOptions = <
	TData = Awaited<ReturnType<typeof userControllerGetUsersList>>,
	TError = ErrorType<unknown>,
>(options?: {
	query?: Partial<
		UseQueryOptions<Awaited<ReturnType<typeof userControllerGetUsersList>>, TError, TData>
	>;
}) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getUserControllerGetUsersListQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof userControllerGetUsersList>>> = ({
		signal,
	}) => userControllerGetUsersList(signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof userControllerGetUsersList>>,
		TError,
		TData
	> & { queryKey: QueryKey };
};

export type UserControllerGetUsersListQueryResult = NonNullable<
	Awaited<ReturnType<typeof userControllerGetUsersList>>
>;
export type UserControllerGetUsersListQueryError = ErrorType<unknown>;

export function useUserControllerGetUsersList<
	TData = Awaited<ReturnType<typeof userControllerGetUsersList>>,
	TError = ErrorType<unknown>,
>(options: {
	query: Partial<
		UseQueryOptions<Awaited<ReturnType<typeof userControllerGetUsersList>>, TError, TData>
	> &
		Pick<
			DefinedInitialDataOptions<
				Awaited<ReturnType<typeof userControllerGetUsersList>>,
				TError,
				TData
			>,
			"initialData"
		>;
}): DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useUserControllerGetUsersList<
	TData = Awaited<ReturnType<typeof userControllerGetUsersList>>,
	TError = ErrorType<unknown>,
>(options?: {
	query?: Partial<
		UseQueryOptions<Awaited<ReturnType<typeof userControllerGetUsersList>>, TError, TData>
	> &
		Pick<
			UndefinedInitialDataOptions<
				Awaited<ReturnType<typeof userControllerGetUsersList>>,
				TError,
				TData
			>,
			"initialData"
		>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useUserControllerGetUsersList<
	TData = Awaited<ReturnType<typeof userControllerGetUsersList>>,
	TError = ErrorType<unknown>,
>(options?: {
	query?: Partial<
		UseQueryOptions<Awaited<ReturnType<typeof userControllerGetUsersList>>, TError, TData>
	>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey };

export function useUserControllerGetUsersList<
	TData = Awaited<ReturnType<typeof userControllerGetUsersList>>,
	TError = ErrorType<unknown>,
>(options?: {
	query?: Partial<
		UseQueryOptions<Awaited<ReturnType<typeof userControllerGetUsersList>>, TError, TData>
	>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
	const queryOptions = getUserControllerGetUsersListQueryOptions(options);

	const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

	query.queryKey = queryOptions.queryKey;

	return query;
}

export const userControllerBlockUser = (id: string) => {
	return authInstance<UserControllerBlockUser200>({
		url: `/api/user/blockUser/${id}`,
		method: "PUT",
	});
};

export const getUserControllerBlockUserMutationOptions = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof userControllerBlockUser>>,
		TError,
		{ id: string },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof userControllerBlockUser>>,
	TError,
	{ id: string },
	TContext
> => {
	const { mutation: mutationOptions } = options ?? {};

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof userControllerBlockUser>>,
		{ id: string }
	> = (props) => {
		const { id } = props ?? {};

		return userControllerBlockUser(id);
	};

	return { mutationFn, ...mutationOptions };
};

export type UserControllerBlockUserMutationResult = NonNullable<
	Awaited<ReturnType<typeof userControllerBlockUser>>
>;

export type UserControllerBlockUserMutationError = ErrorType<unknown>;

export const useUserControllerBlockUser = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof userControllerBlockUser>>,
		TError,
		{ id: string },
		TContext
	>;
}): UseMutationResult<
	Awaited<ReturnType<typeof userControllerBlockUser>>,
	TError,
	{ id: string },
	TContext
> => {
	const mutationOptions = getUserControllerBlockUserMutationOptions(options);

	return useMutation(mutationOptions);
};
export const userControllerGetDashboardCount = (signal?: AbortSignal) => {
	return authInstance<DashboardCount>({ url: `/api/user/dashboard-count`, method: "GET", signal });
};

export const getUserControllerGetDashboardCountQueryKey = () => {
	return [`/api/user/dashboard-count`] as const;
};

export const getUserControllerGetDashboardCountQueryOptions = <
	TData = Awaited<ReturnType<typeof userControllerGetDashboardCount>>,
	TError = ErrorType<unknown>,
>(options?: {
	query?: Partial<
		UseQueryOptions<Awaited<ReturnType<typeof userControllerGetDashboardCount>>, TError, TData>
	>;
}) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getUserControllerGetDashboardCountQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof userControllerGetDashboardCount>>> = ({
		signal,
	}) => userControllerGetDashboardCount(signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof userControllerGetDashboardCount>>,
		TError,
		TData
	> & { queryKey: QueryKey };
};

export type UserControllerGetDashboardCountQueryResult = NonNullable<
	Awaited<ReturnType<typeof userControllerGetDashboardCount>>
>;
export type UserControllerGetDashboardCountQueryError = ErrorType<unknown>;

export function useUserControllerGetDashboardCount<
	TData = Awaited<ReturnType<typeof userControllerGetDashboardCount>>,
	TError = ErrorType<unknown>,
>(options: {
	query: Partial<
		UseQueryOptions<Awaited<ReturnType<typeof userControllerGetDashboardCount>>, TError, TData>
	> &
		Pick<
			DefinedInitialDataOptions<
				Awaited<ReturnType<typeof userControllerGetDashboardCount>>,
				TError,
				TData
			>,
			"initialData"
		>;
}): DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useUserControllerGetDashboardCount<
	TData = Awaited<ReturnType<typeof userControllerGetDashboardCount>>,
	TError = ErrorType<unknown>,
>(options?: {
	query?: Partial<
		UseQueryOptions<Awaited<ReturnType<typeof userControllerGetDashboardCount>>, TError, TData>
	> &
		Pick<
			UndefinedInitialDataOptions<
				Awaited<ReturnType<typeof userControllerGetDashboardCount>>,
				TError,
				TData
			>,
			"initialData"
		>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useUserControllerGetDashboardCount<
	TData = Awaited<ReturnType<typeof userControllerGetDashboardCount>>,
	TError = ErrorType<unknown>,
>(options?: {
	query?: Partial<
		UseQueryOptions<Awaited<ReturnType<typeof userControllerGetDashboardCount>>, TError, TData>
	>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey };

export function useUserControllerGetDashboardCount<
	TData = Awaited<ReturnType<typeof userControllerGetDashboardCount>>,
	TError = ErrorType<unknown>,
>(options?: {
	query?: Partial<
		UseQueryOptions<Awaited<ReturnType<typeof userControllerGetDashboardCount>>, TError, TData>
	>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
	const queryOptions = getUserControllerGetDashboardCountQueryOptions(options);

	const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

	query.queryKey = queryOptions.queryKey;

	return query;
}
