import { Box, Typography, Switch, FormControlLabel } from "@mui/material";
import { Field, useFormikContext } from "formik";
import { useTranslation } from "react-i18next";
import type { UpdateCurrencyCompanyDto } from "@api/services/models";
import DescriptionIcon from "@mui/icons-material/Description";
import SettingsIcon from "@mui/icons-material/Settings";
import EmailIcon from "@mui/icons-material/Email";
import VisibilityIcon from "@mui/icons-material/Visibility";
import { TextFormField } from "@shared/components/FormFields/TextFormField";

interface ExtendedFormValues extends UpdateCurrencyCompanyDto {
	autoGenerateInvoices?: boolean;
	invoicePrefix?: string;
	startingNumber?: string;
	invoiceFooterText?: string;
	sendInvoiceOnOrderConfirmation?: boolean;
	sendInvoiceOnPaymentCompletion?: boolean;
	sendCopyToStoreEmail?: boolean;
}

const InvoiceAutomationForm = () => {
	const { t } = useTranslation();
	const { setFieldValue, values } = useFormikContext<ExtendedFormValues>();

	return (
		<Box>
			<Typography variant="h3" textAlign="center">
				{t("getStarted.invoiceAutomation.title", {
					defaultValue: "Invoice automation",
				})}
			</Typography>
			<Typography variant="h6" my={2} color={"secondary.dark"} fontWeight={500} textAlign="center">
				{t("getStarted.invoiceAutomation.subtitle", {
					defaultValue: "Configure how invoices are generated and sent",
				})}
			</Typography>

			{/* Auto-generate invoices */}
			<Box
				sx={{
					display: "flex",
					justifyContent: "space-between",
					alignItems: "center",
					mt: 3,
					p: 2,
					border: 1,
					borderColor: "grey.300",
					borderRadius: 2,
				}}
			>
				<Box sx={{ display: "flex", alignItems: "center", gap: 2 }}>
					<DescriptionIcon sx={{ fontSize: 32, color: "primary.main" }} />
					<Box>
						<Typography variant="h6" fontWeight={600}>
							{t("getStarted.invoiceAutomation.autoGenerate", {
								defaultValue: "Auto-generate invoices",
							})}
						</Typography>
						<Typography variant="body2" color="text.secondary">
							{t("getStarted.invoiceAutomation.autoGenerateDescription", {
								defaultValue: "Automatically create invoices when orders are placed",
							})}
						</Typography>
					</Box>
				</Box>
				<FormControlLabel
					control={
						<Switch
							checked={values.autoGenerateInvoices ?? true}
							onChange={(e) => setFieldValue("autoGenerateInvoices", e.target.checked)}
							color="primary"
						/>
					}
					label=""
				/>
			</Box>

			{/* Invoice Settings */}
			<Box mt={4}>
				<Box sx={{ display: "flex", alignItems: "center", gap: 1, mb: 3 }}>
					<SettingsIcon sx={{ fontSize: 24, color: "primary.main" }} />
					<Typography variant="h6" fontWeight={600}>
						{t("getStarted.invoiceAutomation.invoiceSettings", {
							defaultValue: "Invoice Settings",
						})}
					</Typography>
				</Box>

				<Box mb={3}>
					<Field
						name="invoicePrefix"
						label={t("getStarted.invoiceAutomation.invoicePrefix", {
							defaultValue: "Invoice Prefix",
						})}
						component={TextFormField}
						placeholder="INV-"
					/>
					<Typography variant="caption" color="text.secondary" sx={{ mt: 0.5, display: "block" }}>
						{t("getStarted.invoiceAutomation.invoicePrefixExample", {
							defaultValue: "Example: INV-001",
						})}
					</Typography>
				</Box>

				<Box mb={3}>
					<Field
						name="startingNumber"
						label={t("getStarted.invoiceAutomation.startingNumber", {
							defaultValue: "Starting Number",
						})}
						component={TextFormField}
						type="number"
						placeholder="1"
					/>
					<Typography variant="caption" color="text.secondary" sx={{ mt: 0.5, display: "block" }}>
						{t("getStarted.invoiceAutomation.startingNumberDescription", {
							defaultValue: "Invoice numbering starts from this",
						})}
					</Typography>
				</Box>

				<Box mb={3}>
					<Field
						name="invoiceFooterText"
						label={t("getStarted.invoiceAutomation.invoiceFooterText", {
							defaultValue: "Invoice Footer Text",
						})}
						component={TextFormField}
						multiline
						rows={4}
						placeholder={t("getStarted.invoiceAutomation.invoiceFooterTextPlaceholder", {
							defaultValue:
								"Thank you for your business! For queries, contact support@yourstore.com",
						})}
					/>
				</Box>
			</Box>

			{/* Email Delivery */}
			<Box mt={4}>
				<Box sx={{ display: "flex", alignItems: "center", gap: 1, mb: 3 }}>
					<EmailIcon sx={{ fontSize: 24, color: "primary.main" }} />
					<Typography variant="h6" fontWeight={600}>
						{t("getStarted.invoiceAutomation.emailDelivery", {
							defaultValue: "Email Delivery",
						})}
					</Typography>
				</Box>

				<Box
					sx={{
						display: "flex",
						justifyContent: "space-between",
						alignItems: "center",
						mb: 2,
						p: 2,
						border: 1,
						borderColor: "grey.300",
						borderRadius: 2,
					}}
				>
					<Box>
						<Typography variant="body1" fontWeight={600}>
							{t("getStarted.invoiceAutomation.sendOnOrderConfirmation", {
								defaultValue: "Send invoice on order confirmation",
							})}
						</Typography>
						<Typography variant="body2" color="text.secondary">
							{t("getStarted.invoiceAutomation.sendOnOrderConfirmationDescription", {
								defaultValue: "Customer receives invoice immediately",
							})}
						</Typography>
					</Box>
					<FormControlLabel
						control={
							<Switch
								checked={values.sendInvoiceOnOrderConfirmation ?? true}
								onChange={(e) => setFieldValue("sendInvoiceOnOrderConfirmation", e.target.checked)}
								color="primary"
							/>
						}
						label=""
					/>
				</Box>

				<Box
					sx={{
						display: "flex",
						justifyContent: "space-between",
						alignItems: "center",
						mb: 2,
						p: 2,
						border: 1,
						borderColor: "grey.300",
						borderRadius: 2,
					}}
				>
					<Box>
						<Typography variant="body1" fontWeight={600}>
							{t("getStarted.invoiceAutomation.sendOnPaymentCompletion", {
								defaultValue: "Send invoice on payment completion",
							})}
						</Typography>
						<Typography variant="body2" color="text.secondary">
							{t("getStarted.invoiceAutomation.sendOnPaymentCompletionDescription", {
								defaultValue: "For COD orders, sent after delivery",
							})}
						</Typography>
					</Box>
					<FormControlLabel
						control={
							<Switch
								checked={values.sendInvoiceOnPaymentCompletion ?? false}
								onChange={(e) => setFieldValue("sendInvoiceOnPaymentCompletion", e.target.checked)}
								color="primary"
							/>
						}
						label=""
					/>
				</Box>

				<Box
					sx={{
						display: "flex",
						justifyContent: "space-between",
						alignItems: "center",
						mb: 2,
						p: 2,
						border: 1,
						borderColor: "grey.300",
						borderRadius: 2,
					}}
				>
					<Box>
						<Typography variant="body1" fontWeight={600}>
							{t("getStarted.invoiceAutomation.sendCopyToStoreEmail", {
								defaultValue: "Send copy to store email",
							})}
						</Typography>
						<Typography variant="body2" color="text.secondary">
							{t("getStarted.invoiceAutomation.sendCopyToStoreEmailDescription", {
								defaultValue: "Keep a copy of all invoices",
							})}
						</Typography>
					</Box>
					<FormControlLabel
						control={
							<Switch
								checked={values.sendCopyToStoreEmail ?? true}
								onChange={(e) => setFieldValue("sendCopyToStoreEmail", e.target.checked)}
								color="primary"
							/>
						}
						label=""
					/>
				</Box>
			</Box>

			{/* Invoice Preview */}
			<Box
				sx={{
					display: "flex",
					alignItems: "center",
					gap: 2,
					mt: 4,
					p: 2,
					border: 1,
					borderColor: "grey.300",
					borderRadius: 2,
				}}
			>
				<VisibilityIcon sx={{ fontSize: 32, color: "primary.main" }} />
				<Box>
					<Typography variant="h6" fontWeight={600}>
						{t("getStarted.invoiceAutomation.invoicePreview", {
							defaultValue: "Invoice Preview",
						})}
					</Typography>
					<Typography variant="body2" color="text.secondary">
						{t("getStarted.invoiceAutomation.invoicePreviewDescription", {
							defaultValue:
								"You can customize the invoice template design in store settings after completing onboarding.",
						})}
					</Typography>
				</Box>
			</Box>
		</Box>
	);
};

export default InvoiceAutomationForm;
