/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { Company } from "./company";
import type { AdminUsersListDtoCurrency } from "./adminUsersListDtoCurrency";
import type { UserPlans } from "./userPlans";

export interface AdminUsersListDto {
	company: Company[];
	createdAt: string;
	/** @nullable */
	currency?: AdminUsersListDtoCurrency;
	/** @nullable */
	currency_id: string | null;
	email: string;
	id: string;
	isActive: boolean;
	isAdmin: boolean;
	isExist: boolean;
	/** @nullable */
	name: string | null;
	password: string;
	/** @nullable */
	phone: string | null;
	/** @nullable */
	resetToken: string | null;
	/** @nullable */
	resetTokenExpiry: string | null;
	/** @nullable */
	storeName: string | null;
	/** @nullable */
	updatedAt: string | null;
	UserPlans: UserPlans[];
}
