/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { BillingAddressCountry } from "./billingAddressCountry";
import type { BillingAddressState } from "./billingAddressState";

export interface BillingAddress {
	address: string;
	city: string;
	/** @nullable */
	country?: BillingAddressCountry;
	/** @nullable */
	country_id: string | null;
	/** @nullable */
	country_name: string | null;
	createdAt: string;
	id: string;
	isExist: boolean;
	/** @nullable */
	state?: BillingAddressState;
	/** @nullable */
	state_id: string | null;
	/** @nullable */
	state_name: string | null;
	/** @nullable */
	updatedAt: string | null;
	zip: string;
}
