/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */

export interface BillingAddressDto {
	address: string;
	city: string;
	/** @nullable */
	country_id: string | null;
	/** @nullable */
	country_name: string | null;
	createdAt: string;
	id: string;
	isExist: boolean;
	/** @nullable */
	state_id: string | null;
	/** @nullable */
	state_name: string | null;
	/** @nullable */
	updatedAt: string | null;
	zip: string;
}
