/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { ChatMessageDto } from "./chatMessageDto";

export interface ChatDto {
	/** Base64 strings (no data URL prefix) for images the AI can see */
	imageBase64?: string[];
	messages: ChatMessageDto[];
}
