/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { ProductItemDto } from "./productItemDto";
import type { ShippingDetailsDto } from "./shippingDetailsDto";

export interface CheckoutInvoiceCreateDto {
	/** The currency of the transaction */
	currency: string;
	/** Customer's email address */
	email: string;
	/** Customer's full name */
	name: string;
	/** Customer's phone number */
	phone: string;
	products: ProductItemDto[];
	shippingDetails: ShippingDetailsDto;
	/** The ID of the user creating the invoice */
	user_id: string;
}
