/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { CompanyCountry } from "./companyCountry";
import type { CompanyState } from "./companyState";
import type { User } from "./user";

export interface Company {
	/** @nullable */
	address: string | null;
	/** @nullable */
	city: string | null;
	/** @nullable */
	country?: CompanyCountry;
	/** @nullable */
	country_id: string | null;
	createdAt: string;
	id: string;
	isExist: boolean;
	/** @nullable */
	lineOfBusiness: string | null;
	/** @nullable */
	logo: string | null;
	name: string;
	/** @nullable */
	phone: string | null;
	/** @nullable */
	short_description: string | null;
	/** @nullable */
	state?: CompanyState;
	/** @nullable */
	state_id: string | null;
	/** @nullable */
	updatedAt: string | null;
	user?: User;
	user_id: string;
	/** @nullable */
	vat: string | null;
	/** @nullable */
	zip: string | null;
}
