/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */

export interface CouponsDto {
	code: string;
	createdAt: string;
	discount: number;
	end_date: string;
	id: string;
	is_active: boolean;
	isExist: boolean;
	start_date: string;
	/** @nullable */
	updatedAt: string | null;
	user_id: string;
}
