/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { SuccessResponseDto } from "./successResponseDto";
import type { CouponsControllerUpdate200AllOf } from "./couponsControllerUpdate200AllOf";

export type CouponsControllerUpdate200 = SuccessResponseDto & CouponsControllerUpdate200AllOf;
