/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */

export interface CreateNotificationDto {
	body: string;
	/** @nullable */
	meta?: string | null;
	/** @nullable */
	metaType?: string | null;
	title: string;
	user_id: string;
}
