/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { CreateBillingAddressDto } from "./createBillingAddressDto";
import type { CreateCustomerWithAddressDtoOption } from "./createCustomerWithAddressDtoOption";
import type { CreateShippingAddressDto } from "./createShippingAddressDto";

export interface CreateCustomerWithAddressDto {
	billingDetails?: CreateBillingAddressDto;
	/** @nullable */
	currencies_id?: string | null;
	display_name: string;
	/** @nullable */
	email?: string | null;
	fromStore?: boolean;
	/** @nullable */
	gstIn?: string | null;
	name: string;
	option: CreateCustomerWithAddressDtoOption;
	phone: string;
	shippingDetails?: CreateShippingAddressDto;
	user_id: string;
	/** @nullable */
	website?: string | null;
}
