/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { CreateProductWithTaxDtoType } from "./createProductWithTaxDtoType";

export interface CreateProductWithTaxDto {
	currency_id: string;
	/** @nullable */
	description?: string | null;
	/** @nullable */
	hsnCode_id?: string | null;
	name: string;
	price: number;
	/**
	 * List of tax id strings associated with the product
	 * @nullable
	 */
	tax?: string[] | null;
	type: CreateProductWithTaxDtoType;
	unit_id: string;
	user_id: string;
}
