/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { CreateInvoiceSettingsDtoInvoiceHeadingType } from "./createInvoiceSettingsDtoInvoiceHeadingType";

export interface CreateInvoiceSettingsDto {
	autoArchive?: boolean;
	companyAddressTemplate: string;
	customerBillingAddressTemplate: string;
	customerShippingAddressTemplate: string;
	dueNotice: number;
	/** @nullable */
	footer?: string | null;
	enableReminder?: boolean;
	reminderInterval?: number;
	invoiceHeadingType?: CreateInvoiceSettingsDtoInvoiceHeadingType;
	invoicePrefix: string;
	invoiceTemplateId: string;
	/** @nullable */
	notes?: string | null;
	overDueNotice: number;
	user_id: string;
}
