/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */

export type CreateGateWayDetailsDtoType =
	(typeof CreateGateWayDetailsDtoType)[keyof typeof CreateGateWayDetailsDtoType];

// eslint-disable-next-line 
export const CreateGateWayDetailsDtoType = {
	Stripe: "Stripe",
	Razorpay: "Razorpay",
} as const;
