/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { CreateAIDashboardDtoType } from "./createAIDashboardDtoType";

export interface CreateAIDashboardDto {
	prompt: string;
	query: string;
	title: string;
	type: CreateAIDashboardDtoType;
	user_id: string;
}
