/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { CreateUserPlansDtoPaymentType } from "./createUserPlansDtoPaymentType";

export interface CreateUserPlansDto {
	end_date: string;
	payment_type?: CreateUserPlansDtoPaymentType;
	plan_id: string;
	session_id?: string;
	start_date: string;
	status?: boolean;
	user_id: string;
}
