/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */

export interface CreateTaxDto {
	/** @nullable */
	description?: string | null;
	percentage: number;
	user_id: string;
}
