/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */

/**
 * Operation type: set, add, or subtract
 */
export type CreateInventoryDtoOperation =
	(typeof CreateInventoryDtoOperation)[keyof typeof CreateInventoryDtoOperation];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateInventoryDtoOperation = {
	set: "set",
	add: "add",
	subtract: "subtract",
} as const;
