/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */

export interface CreateUserCompany {
	companyName: string;
	/** @nullable */
	currency_id?: string | null;
	email: string;
	/** Google OAuth token for Google sign-in */
	googleToken?: string;
	isActive?: boolean;
	/** Flag to indicate this is a Google sign-in attempt */
	isGoogleSignIn?: boolean;
	/** @nullable */
	name?: string | null;
	password: string;
	/** @nullable */
	phone?: string | null;
	/** @nullable */
	storeName?: string | null;
}
