/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { CreateInventoryDtoOperation } from "./createInventoryDtoOperation";

export interface CreateInventoryDto {
	/** Amount to add or subtract (required if operation is add or subtract) */
	amount?: number;
	/** Low stock threshold (optional, defaults to 10) */
	lowStockThreshold?: number;
	/** Operation type: set, add, or subtract */
	operation?: CreateInventoryDtoOperation;
	/** Product ID to create inventory for */
	productId: string;
	/** Stock quantity (optional, defaults to 0) */
	quantity?: number;
}
