/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { CustomerBillingAddress } from "./customerBillingAddress";
import type { CustomerCurrencies } from "./customerCurrencies";
import type { CustomerOption } from "./customerOption";
import type { CustomerShippingAddress } from "./customerShippingAddress";
import type { User } from "./user";

export interface Customer {
	/** @nullable */
	billingAddress?: CustomerBillingAddress;
	/** @nullable */
	billingAddress_id: string | null;
	createdAt: string;
	/** @nullable */
	currencies?: CustomerCurrencies;
	/** @nullable */
	currencies_id: string | null;
	display_name: string;
	/** @nullable */
	email: string | null;
	fromStore: boolean;
	/** @nullable */
	gstIn: string | null;
	id: string;
	isExist: boolean;
	name: string;
	option: CustomerOption;
	/** @nullable */
	phone: string | null;
	/** @nullable */
	shippingAddress?: CustomerShippingAddress;
	/** @nullable */
	shippingAddress_id: string | null;
	/** @nullable */
	updatedAt: string | null;
	user?: User;
	user_id: string;
	/** @nullable */
	website: string | null;
}
