/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { BillingAddress } from "./billingAddress";

/**
 * @nullable
 */
export type CustomerBillingAddress = BillingAddress | null;
