/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { ResBulkCustomerDto } from "./resBulkCustomerDto";

export type CustomerControllerCreateBulk201AllOf = {
	result?: ResBulkCustomerDto;
};
