/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */

export type GateWayDetailsDtoType =
	(typeof GateWayDetailsDtoType)[keyof typeof GateWayDetailsDtoType];

// eslint-disable-next-line 
export const GateWayDetailsDtoType = {
	Stripe: "Stripe",
	Razorpay: "Razorpay",
} as const;
