/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { CountInvoiceDto } from "./countInvoiceDto";
import type { BillingAddressDto } from "./billingAddressDto";
import type { GetCustomerWithAddressDtoOption } from "./getCustomerWithAddressDtoOption";
import type { ShippingAddressDto } from "./shippingAddressDto";
import type { CountTotalDueDto } from "./countTotalDueDto";

export interface GetCustomerWithAddressDto {
	_count?: CountInvoiceDto;
	billingAddress?: BillingAddressDto;
	/** @nullable */
	billingAddress_id: string | null;
	createdAt: string;
	/** @nullable */
	currencies_id: string | null;
	display_name: string;
	/** @nullable */
	email: string | null;
	fromStore: boolean;
	/** @nullable */
	gstIn: string | null;
	id: string;
	isExist: boolean;
	name: string;
	option: GetCustomerWithAddressDtoOption;
	phone: string;
	shippingAddress?: ShippingAddressDto;
	/** @nullable */
	shippingAddress_id: string | null;
	totalDue?: CountTotalDueDto;
	/** @nullable */
	updatedAt: string | null;
	user_id: string;
	/** @nullable */
	website: string | null;
}
