/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { InventoryResponseDtoStatus } from "./inventoryResponseDtoStatus";

export interface InventoryResponseDto {
	/** Created at timestamp */
	createdAt: string;
	/** Inventory entry ID */
	id: string;
	/** Last updated timestamp */
	lastUpdated: string;
	/** Low stock threshold */
	lowStockThreshold: number;
	/** Product ID */
	productId: string;
	/** Product name */
	productName: string;
	/** Current stock quantity */
	quantity: number;
	/** Inventory status */
	status: InventoryResponseDtoStatus;
	/** Product unit */
	unit: string;
	/** Updated at timestamp */
	updatedAt: string;
	/** User ID */
	user_id: string;
}
