/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */

/**
 * Inventory status
 */
export type InventoryResponseDtoStatus =
	(typeof InventoryResponseDtoStatus)[keyof typeof InventoryResponseDtoStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InventoryResponseDtoStatus = {
	available: "available",
	partially_available: "partially_available",
	unavailable: "unavailable",
} as const;
