/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { SuccessResponseDto } from "./successResponseDto";
import type { InventoryControllerCreate201AllOf } from "./inventoryControllerCreate201AllOf";

export type InventoryControllerCreate201 = SuccessResponseDto & InventoryControllerCreate201AllOf;
