/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { SuccessResponseDto } from "./successResponseDto";
import type { InvoiceControllerSendInvoicePaymentReceiptManually200AllOf } from "./invoiceControllerSendInvoicePaymentReceiptManually200AllOf";

export type InvoiceControllerSendInvoicePaymentReceiptManually200 = SuccessResponseDto &
	InvoiceControllerSendInvoicePaymentReceiptManually200AllOf;
