/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */

export interface InvoiceTemplate {
	createdAt: string;
	id: string;
	isExist: boolean;
	name: string;
	/** @nullable */
	path: string | null;
	/** @nullable */
	updatedAt: string | null;
	view: string;
}
