/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */

export type InvoiceWithAllDataDtoPaidStatus =
	(typeof InvoiceWithAllDataDtoPaidStatus)[keyof typeof InvoiceWithAllDataDtoPaidStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InvoiceWithAllDataDtoPaidStatus = {
	Paid: "Paid",
	Unpaid: "Unpaid",
} as const;
