/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { InvoiceProductWithAllDataDtoHsnCode } from "./invoiceProductWithAllDataDtoHsnCode";
import type { Invoice } from "./invoice";
import type { ProductWithAllDataDto } from "./productWithAllDataDto";
import type { TaxForInvoiceProducts } from "./taxForInvoiceProducts";

export interface InvoiceProductWithAllDataDto {
	createdAt: string;
	/** @nullable */
	hsnCode?: InvoiceProductWithAllDataDtoHsnCode;
	/** @nullable */
	hsnCode_id: string | null;
	id: string;
	invoice?: Invoice;
	invoice_id: string;
	isExist: boolean;
	price: number;
	product?: ProductWithAllDataDto;
	product_id: string;
	quantity: number;
	tax_forInvoiceProducts?: TaxForInvoiceProducts[];
	total: number;
	/** @nullable */
	updatedAt: string | null;
}
