/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */

export type InvoiceControllerBulkInvoiceSentToMailParams = {
	/**
	 * Array of Invoice IDs
	 */
	ids: string[];
	/**
	 * selected language for email attachments
	 */
	lang?: string;
};
