/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { OpenaiControllerExtractInvoice200Customer } from "./openaiControllerExtractInvoice200Customer";
import type { OpenaiControllerExtractInvoice200LineItemsItem } from "./openaiControllerExtractInvoice200LineItemsItem";

export type OpenaiControllerExtractInvoice200 = {
	currency_code?: string;
	customer?: OpenaiControllerExtractInvoice200Customer;
	date?: string;
	due_date?: string;
	invoice_number?: string;
	line_items?: OpenaiControllerExtractInvoice200LineItemsItem[];
	notes?: string;
	subtotal?: number;
	tax_amount?: number;
	total?: number;
};
