/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */

export type PaymentsControllerGrowlimitlessSuccessParams = {
	session_id: string;
	invoice_id: string;
	user_id: string;
};
