/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */

export type PaymentsPaymentType = (typeof PaymentsPaymentType)[keyof typeof PaymentsPaymentType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PaymentsPaymentType = {
	UPI: "UPI",
	EuropeanBank: "EuropeanBank",
	SwiftCode: "SwiftCode",
	Paypal: "Paypal",
	Stripe: "Stripe",
	Razorpay: "Razorpay",
	Mollie: "Mollie",
	Cash: "Cash",
	Cheque: "Cheque",
	GrowLimitLess: "GrowLimitLess",
	IndianBanks: "IndianBanks",
} as const;
