/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { Currencies } from "./currencies";
import type { PlanFeaturesDto } from "./planFeaturesDto";

export interface PlanWithFeaturesDto {
	createdAt: string;
	currency?: Currencies;
	currency_id: string;
	days: number;
	description: string;
	id: string;
	is_active: boolean;
	isExist: boolean;
	isOneTime: boolean;
	name: string;
	PlanFeatures: PlanFeaturesDto[];
	price: number;
	/** @nullable */
	updatedAt: string | null;
}
