/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { ProductDtoType } from "./productDtoType";

export interface ProductDto {
	createdAt: string;
	/** @nullable */
	description: string | null;
	/** @nullable */
	hsnCode_id: string | null;
	id: string;
	/** @nullable */
	image: string | null;
	includeStore: boolean;
	isExist: boolean;
	name: string;
	type: ProductDtoType;
	unit_id: string;
	/** @nullable */
	updatedAt: string | null;
	user_id: string;
}
