/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */

export type ProductWithAllDataDtoType =
	(typeof ProductWithAllDataDtoType)[keyof typeof ProductWithAllDataDtoType];

// eslint-disable-next-line 
export const ProductWithAllDataDtoType = {
	Service: "Service",
	Good: "Good",
} as const;
