/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { ProductHsnCode } from "./productHsnCode";
import type { ProductType } from "./productType";
import type { ProductUnit } from "./productUnit";
import type { User } from "./user";

export interface Product {
	createdAt: string;
	/** @nullable */
	description: string | null;
	/** @nullable */
	hsnCode?: ProductHsnCode;
	/** @nullable */
	hsnCode_id: string | null;
	id: string;
	images: string[];
	includeQsr: boolean;
	includeStore: boolean;
	isExist: boolean;
	name: string;
	type: ProductType;
	unit?: ProductUnit;
	unit_id: string;
	/** @nullable */
	updatedAt: string | null;
	user?: User;
	user_id: string;
}
