/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */

export interface ProductItemDto {
	hsnId: string;
	price: number;
	product_id: string;
	quantity: number;
	taxes: string[];
	total: number;
}
