/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { CurrenciesDto } from "./currenciesDto";
import type { HSNCode } from "./hSNCode";
import type { ProductPriceBook } from "./productPriceBook";
import type { TaxForProduct } from "./taxForProduct";
import type { ProductWithAllDataDtoType } from "./productWithAllDataDtoType";
import type { ProductUnitDto } from "./productUnitDto";

export interface ProductWithAllDataDto {
	createdAt: string;
	currency?: CurrenciesDto;
	/** @nullable */
	description: string | null;
	hsnCode?: HSNCode;
	/** @nullable */
	hsnCode_id: string | null;
	id: string;
	images: string[];
	includeQsr: boolean;
	includeStore: boolean;
	isExist: boolean;
	name: string;
	priceBook?: ProductPriceBook[];
	tax?: TaxForProduct[];
	type: ProductWithAllDataDtoType;
	unit?: ProductUnitDto;
	unit_id: string;
	/** @nullable */
	updatedAt: string | null;
	user_id: string;
}
