/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { Currencies } from "./currencies";
import type { Product } from "./product";

export interface ProductPriceBook {
	createdAt: string;
	currency?: Currencies;
	currency_id: string;
	id: string;
	isExist: boolean;
	price: number;
	shippingCharges?: number;
	product?: Product;
	product_id: string;
	/** @nullable */
	updatedAt: string | null;
}
