/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { QuotationProductsWithAllDataDtoHsnCode } from "./quotationProductsWithAllDataDtoHsnCode";
import type { ProductWithAllDataDto } from "./productWithAllDataDto";
import type { Quotation } from "./quotation";

export interface QuotationProductsWithAllDataDto {
	createdAt: string;
	/** @nullable */
	hsnCode?: QuotationProductsWithAllDataDtoHsnCode;
	/** @nullable */
	hsnCode_id: string | null;
	id: string;
	isExist: boolean;
	price: number;
	product?: ProductWithAllDataDto;
	product_id: string;
	quantity: number;
	quotation?: Quotation;
	quotation_id: string;
	total: number;
	/** @nullable */
	updatedAt: string | null;
}
