/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { Fulfilled } from "./fulfilled";
import type { Rejected } from "./rejected";

export interface ResBulkCustomerDto {
	fulfilled: Fulfilled[];
	rejected: Rejected[];
}
