/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */

export interface SendPromotionalMailDto {
	attachments?: string[];
	customerIds?: string[];
	html: string;
	isTest?: boolean;
	sendToAllCustomers?: boolean;
	subject: string;
}
