/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { ShippingAddressCountry } from "./shippingAddressCountry";
import type { ShippingAddressState } from "./shippingAddressState";

export interface ShippingAddress {
	address: string;
	city: string;
	/** @nullable */
	country?: ShippingAddressCountry;
	/** @nullable */
	country_id: string | null;
	/** @nullable */
	country_name: string | null;
	createdAt: string;
	id: string;
	isExist: boolean;
	/** @nullable */
	state?: ShippingAddressState;
	/** @nullable */
	state_id: string | null;
	/** @nullable */
	state_name: string | null;
	/** @nullable */
	updatedAt: string | null;
	zip: string;
}
