/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */

export type StoreControllerGetStoreParams = {
	/**
	 * The ID of the user whose store is being queried
	 */
	userId: string;
	/**
	 * The currency code to filter products by currency
	 */
	currency: string;
};
