/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { InvoiceProducts } from "./invoiceProducts";
import type { Tax } from "./tax";

export interface TaxForInvoiceProducts {
	createdAt: string;
	id: string;
	invoiceProduct?: InvoiceProducts;
	invoiceProduct_id: string;
	isExist: boolean;
	tax?: Tax;
	tax_id: string;
	/** @nullable */
	updatedAt: string | null;
}
