/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { QuotationProducts } from "./quotationProducts";
import type { Tax } from "./tax";

export interface TaxForQuotationProducts {
	createdAt: string;
	id: string;
	isExist: boolean;
	quotationProduct?: QuotationProducts;
	quotationProduct_id: string;
	tax?: Tax;
	tax_id: string;
	/** @nullable */
	updatedAt: string | null;
}
