/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { Product } from "./product";
import type { Tax } from "./tax";

export interface TaxForProduct {
	createdAt: string;
	id: string;
	isExist: boolean;
	product?: Product;
	product_id: string;
	tax?: Tax;
	tax_id: string;
	/** @nullable */
	updatedAt: string | null;
}
