/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { UpdateCustomerDtoOption } from "./updateCustomerDtoOption";

export interface UpdateCustomerDto {
	/** @nullable */
	billingAddress_id?: string | null;
	/** @nullable */
	currencies_id?: string | null;
	display_name?: string;
	/** @nullable */
	email?: string | null;
	fromStore?: boolean;
	/** @nullable */
	gstIn?: string | null;
	name?: string;
	option?: UpdateCustomerDtoOption;
	/** @nullable */
	phone?: string | null;
	/** @nullable */
	shippingAddress_id?: string | null;
	user_id?: string;
	/** @nullable */
	website?: string | null;
}
