/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { CreateProductPriceBookDto } from "./createProductPriceBookDto";
import type { UpdateProductWithTaxDtoType } from "./updateProductWithTaxDtoType";

export interface UpdateProductWithTaxDto {
	/** @nullable */
	description?: string | null;
	/** @nullable */
	hsnCode_id?: string | null;
	images?: string[];
	includeStore?: boolean;
	name?: string;
	priceBook: CreateProductPriceBookDto[];
	/**
	 * List of tax id strings associated with the product
	 * @nullable
	 */
	tax?: string[] | null;
	type?: UpdateProductWithTaxDtoType;
	unit_id?: string;
	user_id?: string;
}
