/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */

export type UpdateAIDashboardDtoType =
	(typeof UpdateAIDashboardDtoType)[keyof typeof UpdateAIDashboardDtoType];

// eslint-disable-next-line 
export const UpdateAIDashboardDtoType = {
	Table: "Table",
	Chart: "Chart",
} as const;
