/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */

export type UpdateProductDtoType = (typeof UpdateProductDtoType)[keyof typeof UpdateProductDtoType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateProductDtoType = {
	Service: "Service",
	Good: "Good",
} as const;
