/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */

export type UpdateGateWayDetailsDtoType =
	(typeof UpdateGateWayDetailsDtoType)[keyof typeof UpdateGateWayDetailsDtoType];

// eslint-disable-next-line 
export const UpdateGateWayDetailsDtoType = {
	Stripe: "Stripe",
	Razorpay: "Razorpay",
} as const;
