/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */

export type UpdateProductWithTaxDtoType =
	(typeof UpdateProductWithTaxDtoType)[keyof typeof UpdateProductWithTaxDtoType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateProductWithTaxDtoType = {
	Service: "Service",
	Goods: "Goods",
} as const;
