/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */

/**
 * @nullable
 */
export type UpdateInvoiceWithProductsRecurring =
	| (typeof UpdateInvoiceWithProductsRecurring)[keyof typeof UpdateInvoiceWithProductsRecurring]
	| null;

// eslint-disable-next-line 
export const UpdateInvoiceWithProductsRecurring = {
	Daily: "Daily",
	Weekly: "Weekly",
	Monthly: "Monthly",
	Quarterly: "Quarterly",
	HalfYearly: "HalfYearly",
	Yearly: "Yearly",
} as const;
