/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { UpdateInvoiceSettingsDtoInvoiceHeadingType } from "./updateInvoiceSettingsDtoInvoiceHeadingType";

export interface UpdateInvoiceSettingsDto {
	autoArchive?: boolean;
	companyAddressTemplate?: string;
	customerBillingAddressTemplate?: string;
	customerShippingAddressTemplate?: string;
	dueNotice?: number;
	enableReminder?: boolean;
	/** @nullable */
	footer?: string | null;
	enableReminder?: boolean;
	reminderInterval?: number;
	invoiceHeadingType?: UpdateInvoiceSettingsDtoInvoiceHeadingType;
	invoicePrefix?: string;
	invoiceTemplateId?: string;
	/** @nullable */
	notes?: string | null;
	overDueNotice?: number;
	reminderInterval?: number;
	user_id?: string;
}
