/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */

export interface UpdateCouponsDto {
	code?: string;
	discount?: number;
	end_date?: string;
	is_active?: boolean;
	start_date?: string;
	user_id?: string;
}
