/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */

export type UpdateInvoiceSettingsDtoInvoiceHeadingType =
	(typeof UpdateInvoiceSettingsDtoInvoiceHeadingType)[keyof typeof UpdateInvoiceSettingsDtoInvoiceHeadingType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateInvoiceSettingsDtoInvoiceHeadingType = {
	COMPANY_NAME: "COMPANY_NAME",
	COMPANY_LOGO: "COMPANY_LOGO",
} as const;
