/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { UpdateInventoryDtoOperation } from "./updateInventoryDtoOperation";

export interface UpdateInventoryDto {
	/** Amount to add or subtract (required if operation is add or subtract) */
	amount?: number;
	/** Low stock threshold */
	lowStockThreshold?: number;
	/** Operation type: set, add, or subtract */
	operation?: UpdateInventoryDtoOperation;
	/** Stock quantity */
	quantity?: number;
}
