/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { UserPlansPaymentType } from "./userPlansPaymentType";
import type { Plans } from "./plans";
import type { User } from "./user";

export interface UserPlans {
	createdAt: string;
	end_date: string;
	id: string;
	isExist: boolean;
	payment_type: UserPlansPaymentType;
	plan?: Plans;
	plan_id: string;
	session_id: string;
	start_date: string;
	status: boolean;
	/** @nullable */
	updatedAt: string | null;
	user?: User;
	user_id: string;
}
