/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { Company } from "./company";
import type { UserWithProductsCurrency } from "./userWithProductsCurrency";
import type { ProductWithAllDataDto } from "./productWithAllDataDto";

export interface UserWithProducts {
	company: Company[];
	createdAt: string;
	/** @nullable */
	currency?: UserWithProductsCurrency;
	/** @nullable */
	currency_id: string | null;
	email: string;
	id: string;
	isExist: boolean;
	/** @nullable */
	name: string | null;
	password: string;
	/** @nullable */
	phone: string | null;
	product: ProductWithAllDataDto[];
	/** @nullable */
	resetToken: string | null;
	/** @nullable */
	resetTokenExpiry: string | null;
	/** @nullable */
	updatedAt: string | null;
}
