/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */

export type UserPlansPaymentType = (typeof UserPlansPaymentType)[keyof typeof UserPlansPaymentType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserPlansPaymentType = {
	Stripe: "Stripe",
	Growlimitless: "Growlimitless",
	Razorpay: "Razorpay",
} as const;
