/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { VendorsBillingAddressCountry } from "./vendorsBillingAddressCountry";
import type { VendorsBillingAddressState } from "./vendorsBillingAddressState";

export interface VendorsBillingAddress {
	address: string;
	city: string;
	/** @nullable */
	country?: VendorsBillingAddressCountry;
	/** @nullable */
	country_id: string | null;
	createdAt: string;
	id: string;
	isExist: boolean;
	/** @nullable */
	state?: VendorsBillingAddressState;
	/** @nullable */
	state_id: string | null;
	/** @nullable */
	updatedAt: string | null;
	zip: string;
}
