on:
  push:
    branches:
      - main
name: 🚀 Deploy website on push

jobs:
  create-env-file:
    name: 🛠️ Create .env File
    runs-on: ubuntu-latest
    steps:
      - name: 📄 Create .env File
        run: |
          echo "REACT_APP_BASE_URL=https://api-dev.growinvoice.com" > .env
      - name: 📦 Upload .env File
        uses: actions/upload-artifact@v4
        with:
          name: env-file
          path: .env
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "yarn"
          cache-dependency-path: yarn.lock

      - name: 📦 Install dependencies
        run: |
          yarn add -W caniuse-lite
          yarn install --frozen-lockfile --non-interactive --prefer-offline
          yarn cache clean --all
          yarn run build --if-present

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: "ftp.growinvoice.com"
          username: "u644247801.reactgrowinvoice"
          password: ${{ secrets.GIT_CPANEL_REACT_PWD }}
          local-dir: ./build/
