on:
  push:
    branches:
      - main
name: 🚀 Deploy website on push

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      # create .env file from GitHub Secrets (Settings → Secrets and variables → Actions)
      - name: 📄 Create .env File
        env:
          VITE_APP_BASE_URL: ${{ secrets.VITE_APP_BASE_URL }}
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}
          VITE_FIREBASE_MEASUREMENT_ID: ${{ secrets.VITE_FIREBASE_MEASUREMENT_ID }}
          VITE_GOOGLE_CLIENT_ID: ${{ secrets.VITE_GOOGLE_CLIENT_ID }}
          VITE_GOOGLE_CLIENT_SECRET: ${{ secrets.VITE_GOOGLE_CLIENT_SECRET }}
          VITE_OPENAI_API_KEY: ${{ secrets.VITE_OPENAI_API_KEY }}
        run: |
          echo "VITE_APP_BASE_URL=$VITE_APP_BASE_URL" > .env
          echo "VITE_FIREBASE_PROJECT_ID=$VITE_FIREBASE_PROJECT_ID" >> .env
          echo "VITE_FIREBASE_API_KEY=$VITE_FIREBASE_API_KEY" >> .env
          echo "VITE_FIREBASE_MESSAGING_SENDER_ID=$VITE_FIREBASE_MESSAGING_SENDER_ID" >> .env
          echo "VITE_FIREBASE_APP_ID=$VITE_FIREBASE_APP_ID" >> .env
          echo "VITE_FIREBASE_MEASUREMENT_ID=$VITE_FIREBASE_MEASUREMENT_ID" >> .env
          echo "VITE_GOOGLE_CLIENT_ID=$VITE_GOOGLE_CLIENT_ID" >> .env
          echo "VITE_GOOGLE_CLIENT_SECRET=$VITE_GOOGLE_CLIENT_SECRET" >> .env
          echo "VITE_OPENAI_API_KEY=$VITE_OPENAI_API_KEY" >> .env
      - name: 📦 Upload .env File
        uses: actions/upload-artifact@v4
        with:
          name: env-file
          path: .env

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"
          cache-dependency-path: yarn.lock

      - name: 📦 Install dependencies and build
        run: |
          yarn install --frozen-lockfile --non-interactive --prefer-offline
          yarn cache clean --all
          yarn run build

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: "ftp.growinvoice.com"
          username: "u644247801.reactgrowinvoice"
          password: ${{ secrets.GIT_CPANEL_REACT_PWD }}
          local-dir: ./dist/
